#include "DDGIDebugPass.h"

#include "../DDGIProbeVolume.h"
#include "../GPUDrivenRenderer.h"
#include "../RenderTypes.h"

// Compiled SPIR-V (autogenerated by compile_slang; the shader is flat in
// shaders/ because the CMake glob does not recurse into subdirectories).
#ifdef USE_SLANG
#include "_autogen/ddgi_probe_visualization.slang.h"
#endif

#include <algorithm>
#include <array>
#include <cstring>

namespace demo
{
	DDGIDebugPass::DDGIDebugPass(GPUDrivenRenderer* renderer)
		: m_renderer(renderer)
	{
	}

	void DDGIDebugPass::initResources(rhi::Device& device, uint32_t frameCount)
	{
		shutdownResources();

		if (m_renderer == nullptr)
		{
			return;
		}
		const DDGIProbeVolume& probeVolume = m_renderer->getDDGIProbeVolume();
		const FlaxDDGIResources& flaxResources = m_renderer->getFlaxDDGIResources();
		const bool flaxReady = m_renderer->isFlaxStyleDDGIRequested()
			&& flaxResources.isInitialized()
			&& !flaxResources.getProbesPerCascade().empty();
		const bool currentReady = probeVolume.isInitialized() && probeVolume.getTotalProbes() > 0u;
		if (!flaxReady && !currentReady)
		{
			LOGW("DDGIDebugPass::initResources skipped: no DDGI probe resources are ready");
			return;
		}

		m_device = &device;
		m_frameCount = std::max(frameCount, 1u);
		m_usesFlaxResources = flaxReady;
		m_visualizedCascadeCount = flaxReady
			? static_cast<uint32_t>(flaxResources.getProbesPerCascade().size())
			: 1u;
		m_visualizedProbeCounts.resize(m_visualizedCascadeCount);
		if (flaxReady)
		{
			for (uint32_t cascadeIndex = 0; cascadeIndex < m_visualizedCascadeCount; ++cascadeIndex)
			{
				const glm::uvec3 counts = flaxResources.getProbesPerCascade()[cascadeIndex];
				m_visualizedProbeCounts[cascadeIndex] = counts.x * counts.y * counts.z;
			}
		}
		else
		{
			m_visualizedProbeCounts[0] = probeVolume.getTotalProbes();
		}

		// Sampled views over BOTH irradiance atlases (D4-1 ping-pong): index =
		// frame parity, view = that parity's WRITE atlas — the one the probe
		// update produced this frame (same selection as the lighting path).
		for (uint32_t parity = 0; parity < 2u; ++parity)
		{
			rhi::TextureViewCreateDesc viewDesc{};
			viewDesc.image = flaxReady
				? flaxResources.getProbesIrradianceWrite(parity)
				: probeVolume.getIrradianceAtlasWrite(parity);
			viewDesc.format = rhi::TextureFormat::rgba16Sfloat;
			viewDesc.viewType = rhi::ImageViewType::e2D;
			viewDesc.aspect = rhi::TextureAspect::color;
			viewDesc.baseMipLevel = 0;
			viewDesc.levelCount = 1;
			viewDesc.debugName = flaxReady
				? (parity == 0u ? "flax-ddgi-debug-irradiance-p0"
				                 : "flax-ddgi-debug-irradiance-p1")
				: (parity == 0u ? "ddgi-debug-irradiance-view-p0"
				                 : "ddgi-debug-irradiance-view-p1");
			m_irradianceViews[parity] = device.createTextureView(viewDesc);
		}

		if (flaxReady)
		{
			rhi::TextureViewCreateDesc dataViewDesc{};
			dataViewDesc.image = flaxResources.getProbesData();
			dataViewDesc.format = flaxResources.usesSNORM()
				? rhi::TextureFormat::rgba8Snorm
				: rhi::TextureFormat::rgba16Sfloat;
			dataViewDesc.viewType = rhi::ImageViewType::e2D;
			dataViewDesc.aspect = rhi::TextureAspect::color;
			dataViewDesc.baseMipLevel = 0;
			dataViewDesc.levelCount = 1;
			dataViewDesc.debugName = "flax-ddgi-debug-probe-data";
			m_probeDataView = device.createTextureView(dataViewDesc);
		}

		m_sampler = device.createSampler(rhi::SamplerDesc{
			.magFilter = rhi::Filter::linear,
			.minFilter = rhi::Filter::linear,
			.mipmapMode = rhi::MipmapMode::nearest,
			.addressModeU = rhi::AddressMode::clampToEdge,
			.addressModeV = rhi::AddressMode::clampToEdge,
			.addressModeW = rhi::AddressMode::clampToEdge,
			.debugName = "ddgi-debug-sampler",
		});

		const std::array<rhi::ArgumentBinding, 3> bindings{
			{
				rhi::ArgumentBinding{
					.binding = 0, .type = rhi::ArgumentType::combinedImageSampler,
					.visibility = rhi::ShaderStage::fragment, .arrayCount = 1
				},
				rhi::ArgumentBinding{
					.binding = 1, .type = rhi::ArgumentType::uniformBuffer,
					.visibility = rhi::ShaderStage::allGraphics, .arrayCount = 1
				},
				rhi::ArgumentBinding{
					.binding = 2, .type = rhi::ArgumentType::sampledTexture,
					.visibility = rhi::ShaderStage::vertex, .arrayCount = 1
				},
			}
		};
		m_layout = device.createArgumentLayout(rhi::ArgumentLayoutDesc{
			.bindings = bindings.data(),
			.bindingCount = static_cast<uint32_t>(bindings.size()),
			.debugName = "ddgi-debug",
		});

		const uint32_t uniformCount = m_frameCount * m_visualizedCascadeCount;
		m_tables.resize(uniformCount * 2u);
		m_uniformBuffers.resize(uniformCount);
		for (uint32_t frameIndex = 0; frameIndex < m_frameCount; ++frameIndex)
		{
			for (uint32_t cascadeIndex = 0; cascadeIndex < m_visualizedCascadeCount; ++cascadeIndex)
			{
				const uint32_t uniformIndex =
					frameIndex * m_visualizedCascadeCount + cascadeIndex;
				m_uniformBuffers[uniformIndex] = device.createBuffer(rhi::BufferDesc{
					.size = sizeof(shaderio::DDGIProbeVisualizationUniforms),
					.usage = rhi::BufferUsageFlags::uniform,
					.memoryUsage = rhi::MemoryUsage::cpuToGpu,
					.debugName = "ddgi-debug-uniforms",
				});

				for (uint32_t parity = 0; parity < 2u; ++parity)
				{
					rhi::ArgumentTableHandle& table =
						m_tables[uniformIndex * 2u + parity];
					table = device.createArgumentTable(m_layout);
					const std::array<rhi::ArgumentWrite, 3> writes{
						{
							rhi::ArgumentWrite{
								.binding = 0, .type = rhi::ArgumentType::combinedImageSampler,
								.textureView = m_irradianceViews[parity],
								.sampler = m_sampler,
								.accessIntent = rhi::ArgumentAccessIntent::readWrite,
							},
							rhi::ArgumentWrite{
								.binding = 1, .type = rhi::ArgumentType::uniformBuffer,
								.buffer = m_uniformBuffers[uniformIndex],
								.size = sizeof(shaderio::DDGIProbeVisualizationUniforms),
							},
							rhi::ArgumentWrite{
								.binding = 2, .type = rhi::ArgumentType::sampledTexture,
								.textureView = m_usesFlaxResources
									? m_probeDataView : m_irradianceViews[parity],
								.accessIntent = rhi::ArgumentAccessIntent::readWrite,
							},
						}
					};
					device.updateArgumentTable(
						table, static_cast<uint32_t>(writes.size()), writes.data());
				}
			}
		}

#ifdef USE_SLANG
		const std::array<rhi::PipelineShaderStageDesc, 2> stages{
			{
				rhi::PipelineShaderStageDesc{
					.stage = rhi::ShaderStage::vertex,
					.spirvCode = ddgi_probe_visualization_slang,
					.spirvSize = std::size(ddgi_probe_visualization_slang) * sizeof(uint32_t),
					.entryPoint = "vertexProbeVisMain"
				},
				rhi::PipelineShaderStageDesc{
					.stage = rhi::ShaderStage::fragment,
					.spirvCode = ddgi_probe_visualization_slang,
					.spirvSize = std::size(ddgi_probe_visualization_slang) * sizeof(uint32_t),
					.entryPoint = "fragmentProbeVisMain"
				},
			}
		};
		const std::array<rhi::DynamicState, 2> dynamicStates{
			{
				rhi::DynamicState::viewport,
				rhi::DynamicState::scissor,
			}
		};
		const std::array<rhi::BlendAttachmentState, 1> blendStates{
			{
				rhi::BlendAttachmentState{.blendEnable = false, .colorWriteMask = rhi::ColorComponentFlags::all},
			}
		};
		const std::array<rhi::TextureFormat, 1> colorFormats{{m_renderer->getSceneColorHdrFormat()}};
		const std::array<rhi::ArgumentLayoutHandle, 1> layouts{{m_layout}};
		rhi::GraphicsPipelineDesc desc{
			.shaderStages = stages.data(),
			.shaderStageCount = static_cast<uint32_t>(stages.size()),
			.vertexInput = rhi::VertexInputLayoutDesc{}, // buffer-less procedural sphere
			.rasterState = rhi::RasterState{},
			// Depth test on / write off against the scene depth (reversed-Z:
			// greaterOrEqual, matching the engine's geometry passes).
			.depthState = rhi::DepthState{true, false, rhi::CompareOp::greaterOrEqual},
			.blendStates = blendStates.data(),
			.blendStateCount = static_cast<uint32_t>(blendStates.size()),
			.dynamicStates = dynamicStates.data(),
			.dynamicStateCount = static_cast<uint32_t>(dynamicStates.size()),
			.renderingInfo =
			{
				.colorFormats = colorFormats.data(),
				.colorFormatCount = static_cast<uint32_t>(colorFormats.size()),
				.depthFormat = m_renderer->getSceneDepthFormat(),
			},
			.argumentLayouts = layouts.data(),
			.argumentLayoutCount = static_cast<uint32_t>(layouts.size()),
			.specializationVariant = 0x7409u,
		};
		desc.rasterState.topology = rhi::PrimitiveTopology::triangleList;
		// Cull the hidden half of each procedural sphere. With two-sided
		// drawing and depth writes disabled, back faces can overdraw front faces
		// because both only test against scene depth, producing stripey probes
		// that look like they ignore depth.
		desc.rasterState.cullMode = rhi::CullMode::back;
		desc.rasterState.frontFace = rhi::FrontFace::counterClockwise;
		desc.rasterState.sampleCount = rhi::SampleCount::count1;
		m_pipeline = device.createGraphicsPipeline(desc);
#endif
	}

	void DDGIDebugPass::shutdownResources()
	{
		if (m_device == nullptr)
		{
			return;
		}

		if (!m_pipeline.isNull()) m_device->destroyPipeline(m_pipeline);
		m_pipeline = {};

		for (rhi::ArgumentTableHandle& table : m_tables)
		{
			if (!table.isNull()) m_device->destroyArgumentTable(table);
			table = {};
		}
		m_tables.clear();
		for (rhi::BufferHandle& buffer : m_uniformBuffers)
		{
			if (!buffer.isNull()) m_device->destroyBuffer(buffer);
			buffer = {};
		}
		m_uniformBuffers.clear();

		if (!m_layout.isNull()) m_device->destroyArgumentLayout(m_layout);
		m_layout = {};

		if (!m_probeDataView.isNull()) m_device->destroyTextureView(m_probeDataView);
		m_probeDataView = {};
		if (!m_sampler.isNull()) m_device->destroySampler(m_sampler);
		m_sampler = {};
		for (rhi::TextureViewHandle& view : m_irradianceViews)
		{
			if (!view.isNull()) m_device->destroyTextureView(view);
			view = {};
		}

		m_frameCount = 0;
		m_usesFlaxResources = false;
		m_visualizedCascadeCount = 0;
		m_visualizedProbeCounts.clear();
		m_device = nullptr;
	}

	PassNode::HandleSlice<PassResourceDependency> DDGIDebugPass::getDependencies() const
	{
		// Same attachment contract as the skybox overlay: HDR color as a
		// load/store attachment, scene depth read-only for the depth test.
		// The probe-update -> fragment-sample hazard on the irradiance atlas
		// is covered by DDGIProbeUpdatePass's trailing
		// compute -> compute|fragment barrier (Wave D3-1).
		static const std::array<PassResourceDependency, 2> dependencies = {
			PassResourceDependency::texture(kPassSceneColorHdrHandle, ResourceAccess::readWrite,
			                                rhi::ShaderStage::fragment,
			                                rhi::ResourceState::ColorAttachment),
			PassResourceDependency::texture(kPassSceneDepthHandle, ResourceAccess::read, rhi::ShaderStage::fragment,
			                                rhi::ResourceState::DepthStencilReadOnly),
		};
		return {dependencies.data(), static_cast<uint32_t>(dependencies.size())};
	}

	void DDGIDebugPass::writeUniforms(uint32_t frameIndex,
	                                  uint32_t cascadeIndex,
	                                  const PassContext& context) const
	{
		const DDGIProbeVolume& probeVolume = m_renderer->getDDGIProbeVolume();
		const FlaxDDGIResources& flaxResources = m_renderer->getFlaxDDGIResources();
		const DDGIConfig& config = m_renderer->getDDGIConfig();

		shaderio::DDGIProbeVisualizationUniforms uniforms{};
		// Jittered VP: the spheres must match the jittered scene depth buffer
		// they are tested against (TAA resolves the jitter afterwards).
		uniforms.viewProjection = context.params->cameraUniforms->viewProjection;
		uniforms.totalProbes = m_visualizedProbeCounts[cascadeIndex];
		uniforms.probeRadius = kProbeRadius;
		uniforms.ddgiGamma = config.ddgiGamma;
		uniforms.debugScale = std::max(
			context.params->debugOptions.flaxGIProbeVisualizationScale, 0.0f);
		if (m_usesFlaxResources)
		{
			const rhi::Extent2D atlasExtent = flaxResources.getIrradianceAtlasExtent();
			const glm::uvec3 counts =
				flaxResources.getProbesPerCascade()[cascadeIndex];
			uniforms.probePositionAddress = 0u;
			uniforms.irradianceAtlasWidth = atlasExtent.width;
			uniforms.irradianceAtlasHeight = atlasExtent.height;
			uniforms.irradianceSideLength = FlaxDDGIResources::kProbeResolutionIrradiance;
			const uint32_t mode = 1u
				| (context.params->debugOptions.ddgiDebugActiveProbes ? 2u : 0u);
			uniforms.flaxProbeCountsAndMode =
				shaderio::uvec4{counts.x, counts.y, counts.z, mode};
			const auto& cascades = m_renderer->getFlaxDDGICascadeDescs();
			if (cascadeIndex < cascades.size())
			{
				const DDGICascadeDesc& cascade = cascades[cascadeIndex];
				uniforms.flaxProbeOriginAndSpacing = shaderio::vec4{
					cascade.snappedOrigin.x, cascade.snappedOrigin.y,
					cascade.snappedOrigin.z, cascade.probeSpacing};
				uniforms.flaxProbeScrollAndCascade = shaderio::ivec4{
					cascade.scrollOffset.x, cascade.scrollOffset.y,
					cascade.scrollOffset.z, static_cast<int32_t>(cascadeIndex)};
			}
		}
		else
		{
			const rhi::Extent2D atlasExtent = probeVolume.getIrradianceAtlasExtent();
			uniforms.probePositionAddress = probeVolume.getProbePositionAddress().value;
			uniforms.irradianceAtlasWidth = atlasExtent.width;
			uniforms.irradianceAtlasHeight = atlasExtent.height;
			uniforms.irradianceSideLength = probeVolume.getDesc().irradianceTexelSize;
		}

		// cpuToGpu memory is host-coherent on desktop; no explicit flush needed
		// (same contract as DDGIRayTracePass's uniform upload).
		const uint32_t uniformIndex =
			frameIndex * m_visualizedCascadeCount + cascadeIndex;
		void* dst = m_device->mapBuffer(m_uniformBuffers[uniformIndex]);
		std::memcpy(dst, &uniforms, sizeof(uniforms));
	}

	void DDGIDebugPass::execute(const PassContext& context) const
	{
		if (m_renderer == nullptr || context.commandBuffer == nullptr || context.params == nullptr)
		{
			return;
		}
		// Double gate: current DDGI path AND the ImGui visualize checkbox
		// (both default false) — the default frame stays untouched.
		if (!m_renderer->isDDGIProbeDataPathEnabled() || !context.params->debugOptions.ddgiDebugVisualize)
		{
			return;
		}
		const DDGIProbeVolume& probeVolume = m_renderer->getDDGIProbeVolume();
		const FlaxDDGIResources& flaxResources = m_renderer->getFlaxDDGIResources();
		const bool flaxReady = m_usesFlaxResources
			&& flaxResources.isInitialized() && !m_probeDataView.isNull();
		const bool currentReady = !m_usesFlaxResources
			&& probeVolume.isInitialized()
			&& probeVolume.getProbePositionAddress().isValid();
		if (m_device == nullptr || m_pipeline.isNull()
			|| m_irradianceViews[0].isNull() || m_irradianceViews[1].isNull()
			|| m_visualizedCascadeCount == 0u
			|| m_visualizedProbeCounts.size() != m_visualizedCascadeCount
			|| (!flaxReady && !currentReady)
			|| context.params->cameraUniforms == nullptr)
		{
			return;
		}
		uint32_t parity = static_cast<uint32_t>(m_renderer->getTemporalFrameCounter() & 1u);
		if(m_usesFlaxResources)
		{
			const FlaxGIOutputSelection output =
				m_renderer->getFlaxDDGIPublishedOutputSelection();
			if(!output.valid) return;
			parity = output.parity;
		}
		const uint32_t frameIndex = context.frameIndex;
		if (frameIndex >= m_frameCount)
		{
			return;
		}

		const uint32_t availableCascadeCount = m_usesFlaxResources
			? std::min(
				m_visualizedCascadeCount,
				static_cast<uint32_t>(m_renderer->getFlaxDDGICascadeDescs().size()))
			: 1u;
		if (availableCascadeCount == 0u)
		{
			return;
		}
		const int requestedCascade =
			context.params->debugOptions.ddgiDebugCascadeIndex;
		const uint32_t selectedCascade = requestedCascade >= 0
			? std::min(static_cast<uint32_t>(requestedCascade), availableCascadeCount - 1u)
			: 0u;

		const GPUDrivenRenderer::ScreenPassTargets targets = m_renderer->getScreenColorDepthTargets();
		if (!targets.valid)
		{
			return;
		}

		if (requestedCascade >= 0)
		{
			writeUniforms(frameIndex, selectedCascade, context);
		}
		else
		{
			for (uint32_t cascadeIndex = 0; cascadeIndex < availableCascadeCount; ++cascadeIndex)
				writeUniforms(frameIndex, cascadeIndex, context);
		}

		context.commandBuffer->beginEvent("DDGIDebugPass");

		const rhi::RenderTargetDesc colorTarget{
			.texture = {},
			.view = targets.colorView,
			.state = rhi::ResourceState::ColorAttachment,
			.loadOp = rhi::LoadOp::load,
			.storeOp = rhi::StoreOp::store,
		};
		const rhi::DepthTargetDesc depthTarget{
			.texture = {},
			.view = targets.depthView,
			.state = rhi::ResourceState::DepthStencilReadOnly,
			.loadOp = rhi::LoadOp::load,
			.storeOp = rhi::StoreOp::store,
			.clearValue = {0.0f, 0},
		};

		rhi::RenderEncoder* enc = context.commandBuffer->beginRenderPass(rhi::RenderPassDesc{
			.renderArea = {{0, 0}, targets.extent},
			.colorTargets = &colorTarget,
			.colorTargetCount = 1,
			.depthTarget = &depthTarget,
		});
		enc->setViewport(rhi::Viewport{
			0.0f, 0.0f, static_cast<float>(targets.extent.width),
			static_cast<float>(targets.extent.height), 0.0f, 1.0f
		});
		enc->setScissor(rhi::Rect2D{{0, 0}, targets.extent});

		enc->setPipeline(m_pipeline);

		// Procedural UV sphere: stacks * slices * 6 vertices per instance,
		// one instance per probe (instance id == probe index in the shader).
		constexpr uint32_t kSphereVertexCount =
			static_cast<uint32_t>(shaderio::LDDGIProbeVisStacks * shaderio::LDDGIProbeVisSlices * 6);
		const auto drawCascade = [&](uint32_t cascadeIndex)
		{
			const uint32_t uniformIndex =
				frameIndex * m_visualizedCascadeCount + cascadeIndex;
			const uint32_t tableIndex = uniformIndex * 2u + parity;
			enc->setArgumentTable(rhi::ShaderStage::allGraphics, 0, m_tables[tableIndex]);
			enc->draw(rhi::DrawDesc{
				.vertexCount = kSphereVertexCount,
				.instanceCount = m_visualizedProbeCounts[cascadeIndex],
				.firstVertex = 0,
				.firstInstance = 0
			});
		};
		if (requestedCascade >= 0)
		{
			drawCascade(selectedCascade);
		}
		else
		{
			// Draw coarse cascades first so the inner cascade remains legible.
			for (uint32_t cascadeIndex = availableCascadeCount; cascadeIndex > 0u; --cascadeIndex)
				drawCascade(cascadeIndex - 1u);
		}

		context.commandBuffer->endEncoding();
		context.commandBuffer->endEvent();
	}
} // namespace demo
