#include "DDGIProbeUpdatePass.h"

#include "../ArgumentTables.h"
#include "../DDGIProbeVolume.h"
#include "../GPUDrivenRenderer.h"
#include "DDGIRayTracePass.h"

// Compiled SPIR-V (autogenerated by compile_slang; the shaders are flat in
// shaders/ because the CMake glob does not recurse into subdirectories).
#ifdef USE_SLANG
#include "_autogen/ddgi_irradiance_probe_update.slang.h"
#include "_autogen/ddgi_depth_probe_update.slang.h"
#include "_autogen/ddgi_irradiance_border_update.slang.h"
#include "_autogen/ddgi_depth_border_update.slang.h"
#endif

#include <algorithm>
#include <array>

namespace demo
{
	DDGIProbeUpdatePass::DDGIProbeUpdatePass(GPUDrivenRenderer* renderer)
		: m_renderer(renderer)
	{
	}

	void DDGIProbeUpdatePass::initResources(rhi::Device& device)
	{
		shutdownResources();

		if (m_renderer == nullptr)
		{
			return;
		}
		const DDGIProbeVolume& probeVolume = m_renderer->getDDGIProbeVolume();
		if (!probeVolume.isInitialized() || probeVolume.getRadianceBuffer().isNull())
		{
			LOGW("DDGIProbeUpdatePass::initResources skipped: probe volume not ready");
			return;
		}
		// The octahedral side lengths are baked into the shaders' [numthreads]
		// (one workgroup = one probe tile), so a mismatching config cannot run.
		if (probeVolume.getDesc().irradianceTexelSize != kIrradianceTexelSize
			|| probeVolume.getDesc().depthTexelSize != kDepthTexelSize)
		{
			LOGW("DDGIProbeUpdatePass::initResources skipped: texel sizes %u/%u not %u/%u",
			     probeVolume.getDesc().irradianceTexelSize, probeVolume.getDesc().depthTexelSize,
			     kIrradianceTexelSize, kDepthTexelSize);
			return;
		}

		m_device = &device;

		const auto createAtlasView = [&](rhi::TextureHandle texture, rhi::TextureFormat format,
		                                 const char* debugName)
		{
			rhi::TextureViewCreateDesc viewDesc{};
			viewDesc.image = texture;
			viewDesc.format = format;
			viewDesc.viewType = rhi::ImageViewType::e2D;
			viewDesc.aspect = rhi::TextureAspect::color;
			viewDesc.baseMipLevel = 0;
			viewDesc.levelCount = 1;
			viewDesc.debugName = debugName;
			return device.createTextureView(viewDesc);
		};

		// D4-1 ping-pong wiring (approach (2)): one view per physical atlas;
		// the parity table pairs below combine write/read roles per frame.
		m_irradianceViewA = createAtlasView(probeVolume.getIrradianceAtlas(),
		                                    rhi::TextureFormat::rgba16Sfloat,
		                                    "ddgi-update-irradiance-a");
		m_irradianceViewB = createAtlasView(probeVolume.getIrradianceAtlasHistory(),
		                                    rhi::TextureFormat::rgba16Sfloat,
		                                    "ddgi-update-irradiance-b");
		m_depthViewA = createAtlasView(probeVolume.getDepthAtlas(),
		                               rhi::TextureFormat::rg16Sfloat,
		                               "ddgi-update-depth-a");
		m_depthViewB = createAtlasView(probeVolume.getDepthAtlasHistory(),
		                               rhi::TextureFormat::rg16Sfloat,
		                               "ddgi-update-depth-b");
		m_radianceView = createAtlasView(probeVolume.getRadianceBuffer(),
		                                 rhi::TextureFormat::rgba16Sfloat,
		                                 "ddgi-update-radiance");

		// --- Argument layouts ---
		const std::array<rhi::ArgumentBinding, 3> updateBindings{
			{
				rhi::ArgumentBinding{
					.binding = 0, .type = rhi::ArgumentType::storageTexture,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
				rhi::ArgumentBinding{
					.binding = 1, .type = rhi::ArgumentType::storageTexture,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
				rhi::ArgumentBinding{
					.binding = 2, .type = rhi::ArgumentType::storageTexture,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
			}
		};
		m_updateLayout = device.createArgumentLayout(rhi::ArgumentLayoutDesc{
			.bindings = updateBindings.data(),
			.bindingCount = static_cast<uint32_t>(updateBindings.size()),
			.debugName = "ddgi-probe-update",
		});

		const std::array<rhi::ArgumentBinding, 1> borderBindings{
			{
				rhi::ArgumentBinding{
					.binding = 0, .type = rhi::ArgumentType::storageTexture,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
			}
		};
		m_borderLayout = device.createArgumentLayout(rhi::ArgumentLayoutDesc{
			.bindings = borderBindings.data(),
			.bindingCount = static_cast<uint32_t>(borderBindings.size()),
			.debugName = "ddgi-border-update",
		});

		// --- Argument tables (all static: push constants carry frame data) ---
		const auto writeUpdateTable = [&](rhi::ArgumentTableHandle table,
		                                  rhi::TextureViewHandle outView,
		                                  rhi::TextureViewHandle historyView)
		{
			const std::array<rhi::ArgumentWrite, 3> writes{
				{
					rhi::ArgumentWrite{
						.binding = 0, .type = rhi::ArgumentType::storageTexture,
						.textureView = outView,
						.accessIntent = rhi::ArgumentAccessIntent::readWrite,
					},
					rhi::ArgumentWrite{
						.binding = 1, .type = rhi::ArgumentType::storageTexture,
						.textureView = historyView,
						.accessIntent = rhi::ArgumentAccessIntent::readWrite,
					},
					rhi::ArgumentWrite{
						.binding = 2, .type = rhi::ArgumentType::storageTexture,
						.textureView = m_radianceView,
						.accessIntent = rhi::ArgumentAccessIntent::readWrite,
					},
				}
			};
			device.updateArgumentTable(table, static_cast<uint32_t>(writes.size()), writes.data());
		};

		const auto writeBorderTable = [&](rhi::ArgumentTableHandle table, rhi::TextureViewHandle view)
		{
			const rhi::ArgumentWrite write{
				.binding = 0, .type = rhi::ArgumentType::storageTexture,
				.textureView = view,
				.accessIntent = rhi::ArgumentAccessIntent::readWrite,
			};
			device.updateArgumentTable(table, 1, &write);
		};

		// Prebuilt parity pairs (DDGIProbeVolume contract): parity 0 writes
		// set A / reads set B, parity 1 the reverse. Border copy targets the
		// parity's WRITE atlas (the one updated this frame).
		for (uint32_t parity = 0; parity < 2u; ++parity)
		{
			const rhi::TextureViewHandle irradianceOut = parity == 0u ? m_irradianceViewA : m_irradianceViewB;
			const rhi::TextureViewHandle irradianceHistory = parity == 0u ? m_irradianceViewB : m_irradianceViewA;
			const rhi::TextureViewHandle depthOut = parity == 0u ? m_depthViewA : m_depthViewB;
			const rhi::TextureViewHandle depthHistory = parity == 0u ? m_depthViewB : m_depthViewA;

			m_irradianceUpdateTables[parity] = device.createArgumentTable(m_updateLayout);
			writeUpdateTable(m_irradianceUpdateTables[parity], irradianceOut, irradianceHistory);
			m_depthUpdateTables[parity] = device.createArgumentTable(m_updateLayout);
			writeUpdateTable(m_depthUpdateTables[parity], depthOut, depthHistory);

			m_irradianceBorderTables[parity] = device.createArgumentTable(m_borderLayout);
			writeBorderTable(m_irradianceBorderTables[parity], irradianceOut);
			m_depthBorderTables[parity] = device.createArgumentTable(m_borderLayout);
			writeBorderTable(m_depthBorderTables[parity], depthOut);
		}

		// --- Pipelines ---
#ifdef USE_SLANG
		const auto createPipeline = [&](const uint32_t* spirv, size_t wordCount, const char* entryPoint,
		                                rhi::ArgumentLayoutHandle layout, uint32_t pushSize,
		                                uint32_t variant)
		{
			const std::array<rhi::ArgumentLayoutHandle, 1> layouts{{layout}};
			const std::array<rhi::PipelinePushConstantRange, 1> pushRanges{
				{
					rhi::PipelinePushConstantRange{
						.stages = rhi::ShaderStage::compute, .offset = 0, .size = pushSize
					},
				}
			};
			const rhi::ComputePipelineDesc desc{
				.shaderStage =
				rhi::PipelineShaderStageDesc{
					.stage = rhi::ShaderStage::compute,
					.spirvCode = spirv,
					.spirvSize = wordCount * sizeof(uint32_t),
					.entryPoint = entryPoint,
				},
				.argumentLayouts = layouts.data(),
				.argumentLayoutCount = static_cast<uint32_t>(layouts.size()),
				.pushConstantRanges = pushSize > 0u ? pushRanges.data() : nullptr,
				.pushConstantRangeCount = pushSize > 0u ? static_cast<uint32_t>(pushRanges.size()) : 0u,
				.specializationVariant = variant,
			};
			return device.createComputePipeline(desc);
		};

		m_irradianceUpdatePipeline = createPipeline(
			ddgi_irradiance_probe_update_slang, std::size(ddgi_irradiance_probe_update_slang),
			"kernelDDGIIrradianceProbeUpdate", m_updateLayout,
			sizeof(shaderio::DDGIProbeUpdatePush), 0x7405u);
		m_depthUpdatePipeline = createPipeline(
			ddgi_depth_probe_update_slang, std::size(ddgi_depth_probe_update_slang),
			"kernelDDGIDepthProbeUpdate", m_updateLayout,
			sizeof(shaderio::DDGIProbeUpdatePush), 0x7406u);
		m_irradianceBorderPipeline = createPipeline(
			ddgi_irradiance_border_update_slang, std::size(ddgi_irradiance_border_update_slang),
			"kernelDDGIIrradianceBorderUpdate", m_borderLayout, 0u, 0x7407u);
		m_depthBorderPipeline = createPipeline(
			ddgi_depth_border_update_slang, std::size(ddgi_depth_border_update_slang),
			"kernelDDGIDepthBorderUpdate", m_borderLayout, 0u, 0x7408u);
#endif
	}

	void DDGIProbeUpdatePass::shutdownResources()
	{
		if (m_device == nullptr)
		{
			return;
		}

		if (!m_irradianceUpdatePipeline.isNull()) m_device->destroyPipeline(m_irradianceUpdatePipeline);
		if (!m_depthUpdatePipeline.isNull()) m_device->destroyPipeline(m_depthUpdatePipeline);
		if (!m_irradianceBorderPipeline.isNull()) m_device->destroyPipeline(m_irradianceBorderPipeline);
		if (!m_depthBorderPipeline.isNull()) m_device->destroyPipeline(m_depthBorderPipeline);
		m_irradianceUpdatePipeline = {};
		m_depthUpdatePipeline = {};
		m_irradianceBorderPipeline = {};
		m_depthBorderPipeline = {};

		for (uint32_t parity = 0; parity < 2u; ++parity)
		{
			if (!m_irradianceUpdateTables[parity].isNull())
				m_device->destroyArgumentTable(m_irradianceUpdateTables[parity]);
			if (!m_depthUpdateTables[parity].isNull())
				m_device->destroyArgumentTable(m_depthUpdateTables[parity]);
			if (!m_irradianceBorderTables[parity].isNull())
				m_device->destroyArgumentTable(m_irradianceBorderTables[parity]);
			if (!m_depthBorderTables[parity].isNull())
				m_device->destroyArgumentTable(m_depthBorderTables[parity]);
			m_irradianceUpdateTables[parity] = {};
			m_depthUpdateTables[parity] = {};
			m_irradianceBorderTables[parity] = {};
			m_depthBorderTables[parity] = {};
		}

		if (!m_updateLayout.isNull()) m_device->destroyArgumentLayout(m_updateLayout);
		if (!m_borderLayout.isNull()) m_device->destroyArgumentLayout(m_borderLayout);
		m_updateLayout = {};
		m_borderLayout = {};

		if (!m_radianceView.isNull()) m_device->destroyTextureView(m_radianceView);
		if (!m_depthViewB.isNull()) m_device->destroyTextureView(m_depthViewB);
		if (!m_depthViewA.isNull()) m_device->destroyTextureView(m_depthViewA);
		if (!m_irradianceViewB.isNull()) m_device->destroyTextureView(m_irradianceViewB);
		if (!m_irradianceViewA.isNull()) m_device->destroyTextureView(m_irradianceViewA);
		m_radianceView = {};
		m_depthViewB = {};
		m_depthViewA = {};
		m_irradianceViewB = {};
		m_irradianceViewA = {};

		m_atlasLayoutInitialized = false;
		m_device = nullptr;
	}

	PassNode::HandleSlice<PassResourceDependency> DDGIProbeUpdatePass::getDependencies() const
	{
		// The radiance write -> read hazard is covered by DDGIRayTracePass's
		// trailing compute->compute barrier; the atlases are private to the
		// DDGI passes and synchronized with internal barriers below.
		return {nullptr, 0};
	}

	void DDGIProbeUpdatePass::execute(const PassContext& context) const
	{
		if (m_renderer == nullptr || context.commandBuffer == nullptr)
		{
			return;
		}
		// DDGI master gate (defaults to false): the default frame is untouched.
		if (!m_renderer->getDDGIConfig().enabled)
		{
			return;
		}
		const DDGIProbeVolume& probeVolume = m_renderer->getDDGIProbeVolume();
		if (m_device == nullptr || !probeVolume.isInitialized() || probeVolume.getTotalProbes() == 0u
			|| m_irradianceUpdatePipeline.isNull() || m_depthUpdatePipeline.isNull()
			|| m_irradianceBorderPipeline.isNull() || m_depthBorderPipeline.isNull())
		{
			static bool s_logged = false;
			if (!s_logged)
			{
				LOGW("DDGIProbeUpdatePass skipped: resources not ready (volume=%d pipelines=%d%d%d%d)",
				     probeVolume.isInitialized() ? 1 : 0,
				     m_irradianceUpdatePipeline.isNull() ? 0 : 1, m_depthUpdatePipeline.isNull() ? 0 : 1,
				     m_irradianceBorderPipeline.isNull() ? 0 : 1, m_depthBorderPipeline.isNull() ? 0 : 1);
				s_logged = true;
			}
			return;
		}

		const DDGIConfig& config = m_renderer->getDDGIConfig();
		const glm::uvec3 gridDims = probeVolume.getGridDims();
		// Atlas tiling: x*y tiles per row, z rows (DDGIProbeVolume layout).
		const uint32_t probesPerRow = gridDims.x * gridDims.y;
		const uint32_t probeRows = gridDims.z;
		if (probesPerRow == 0u || probeRows == 0u)
		{
			return;
		}

		rhi::CommandBuffer& cmd = *context.commandBuffer;
		cmd.beginEvent("DDGIProbeUpdatePass");

		// First-frame detection (plan: temporalFrameCounter == 0 writes
		// directly). The layout latch extends this to runtime enabling: before
		// the first recorded dispatch the atlases hold no valid history, so
		// the hysteresis blend must be skipped regardless of the counter.
		// NEVER derived from the frames-in-flight ring index (constraint 4).
		const bool firstFrame =
			!m_atlasLayoutInitialized || m_renderer->getTemporalFrameCounter() == 0u;

		// D4-1 ping-pong parity from the MONOTONIC temporal counter (constraint
		// 4 — never context.frameIndex, the frames-in-flight ring index).
		const uint32_t parity =
			static_cast<uint32_t>(m_renderer->getTemporalFrameCounter() & 1u);

		if (!m_atlasLayoutInitialized)
		{
			// Normally DDGIRayTracePass (recorded earlier in the frame) already
			// transitioned the atlases for its history sampling; this latch is
			// the idempotent backup (oldLayout=Undefined is always legal and
			// only discards garbage before the first write) for the corner
			// case where the ray trace pass was skipped.
			const auto makeInitBarrier = [](rhi::TextureHandle texture)
			{
				return rhi::TextureBarrier{
					.texture = texture,
					.before = rhi::ResourceState::Undefined,
					.after = rhi::ResourceState::General,
					.range = {
						.aspect = rhi::TextureAspect::color, .baseMipLevel = 0, .levelCount = 1,
						.baseArrayLayer = 0, .layerCount = 1
					},
				};
			};
			const std::array<rhi::TextureBarrier, 4> initBarriers{
				{
					makeInitBarrier(probeVolume.getIrradianceAtlas()),
					makeInitBarrier(probeVolume.getIrradianceAtlasHistory()),
					makeInitBarrier(probeVolume.getDepthAtlas()),
					makeInitBarrier(probeVolume.getDepthAtlasHistory()),
				}
			};
			cmd.resourceBarrier(initBarriers.data(), static_cast<uint32_t>(initBarriers.size()),
			                    nullptr, 0);
			m_atlasLayoutInitialized = true;
		}

		// Same-frame rotation as DDGIRayTracePass: the update kernels
		// reconstruct the traced ray directions from these columns.
		const glm::mat3 rotation =
			DDGIRayTracePass::makeRayRotation(m_renderer->getTemporalFrameCounter());

		shaderio::DDGIProbeUpdatePush push{};
		push.rotationCol0 = glm::vec4(rotation[0], 0.0f);
		push.rotationCol1 = glm::vec4(rotation[1], 0.0f);
		push.rotationCol2 = glm::vec4(rotation[2], 0.0f);
		push.raysPerProbe = std::max(probeVolume.getDesc().raysPerProbe, 1u);
		push.probesPerRow = probesPerRow;
		push.firstFrame = firstFrame ? 1u : 0u;
		push.hysteresis = config.hysteresis;
		push.ddgiGamma = config.ddgiGamma;
		push.depthSharpness = config.depthSharpness;
		push.maxDistance = config.maxDistance;
		// Staggered update (Wave D4-2): the offset is re-clamped against the
		// current stride so a runtime stride shrink can never strand it out of
		// range (which would make every probe pass-through). stride <= 1
		// degenerates to the full per-frame update.
		const uint32_t updateStride = std::max(config.updateStride, 1u);
		push.updateOffset = m_renderer->getDDGIUpdateOffset() % updateStride;
		push.updateStride = updateStride;

		// One workgroup per probe tile for all four dispatches.
		const rhi::DispatchDesc probeDispatch{probesPerRow, probeRows, 1u};

		// --- Irradiance + depth probe updates (independent: different atlases,
		// both only read the radiance scratch) ---
		cmd.beginEvent("IrradianceProbeUpdate");
		{
			rhi::ComputeEncoder* encoder = cmd.beginComputePass();
			encoder->setPipeline(m_irradianceUpdatePipeline);
			encoder->setArgumentTable(0, m_irradianceUpdateTables[parity]);
			encoder->setRootConstants(kPrimaryRootConstantsSlot, &push, sizeof(push));
			encoder->dispatch(probeDispatch);
			cmd.endEncoding();
		}
		cmd.endEvent();

		cmd.beginEvent("DepthProbeUpdate");
		{
			rhi::ComputeEncoder* encoder = cmd.beginComputePass();
			encoder->setPipeline(m_depthUpdatePipeline);
			encoder->setArgumentTable(0, m_depthUpdateTables[parity]);
			encoder->setRootConstants(kPrimaryRootConstantsSlot, &push, sizeof(push));
			encoder->dispatch(probeDispatch);
			cmd.endEncoding();
		}
		cmd.endEvent();

		// Interior texel writes -> border copy reads of the same atlases.
		cmd.barrier(rhi::StageFlags::compute, rhi::StageFlags::compute,
		            rhi::HazardFlags::textureWrites);

		// --- Border updates (octahedral wrap copy into each tile's 1px ring) ---
		cmd.beginEvent("IrradianceBorderUpdate");
		{
			rhi::ComputeEncoder* encoder = cmd.beginComputePass();
			encoder->setPipeline(m_irradianceBorderPipeline);
			encoder->setArgumentTable(0, m_irradianceBorderTables[parity]);
			encoder->dispatch(probeDispatch);
			cmd.endEncoding();
		}
		cmd.endEvent();

		cmd.beginEvent("DepthBorderUpdate");
		{
			rhi::ComputeEncoder* encoder = cmd.beginComputePass();
			encoder->setPipeline(m_depthBorderPipeline);
			encoder->setArgumentTable(0, m_depthBorderTables[parity]);
			encoder->dispatch(probeDispatch);
			cmd.endEncoding();
		}
		cmd.endEvent();

		// Finished atlases -> future consumers (SampleProbe in the lighting
		// pass, D3-1; fragment included for any debug visualization reads).
		cmd.barrier(rhi::StageFlags::compute,
		            rhi::StageFlags::compute | rhi::StageFlags::fragmentShader,
		            rhi::HazardFlags::textureWrites);

		cmd.endEvent(); // DDGIProbeUpdatePass
	}
} // namespace demo
