#include "DDGIRayTracePass.h"

#include "../DDGIProbeVolume.h"
#include "../GPUDrivenRenderer.h"
#include "../RenderTypes.h"
#include "GlobalSDFPass.h"

// Compiled SPIR-V (autogenerated by compile_slang; the shader is flat in
// shaders/ because the CMake glob does not recurse into subdirectories).
#ifdef USE_SLANG
#include "_autogen/ddgi_gi_sdf_rays.slang.h"
#endif

#include <glm/gtc/quaternion.hpp>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <random>

namespace demo
{
	namespace
	{
		// First-version constant sky radiance for ray misses (IBL cubemap wiring
		// deferred; documented as a plan deviation in ddgi-implementation-plan.md).
		constexpr float kSkyColorR = 0.35f;
		constexpr float kSkyColorG = 0.45f;
		constexpr float kSkyColorB = 0.65f;

		// Uniform random rotation matrix (Shoemake's uniform quaternion method)
		// seeded by the monotonically increasing temporal frame counter — NEVER
		// the frames-in-flight ring index (DDGI hard constraint 4).
		glm::mat3 makeRandomRotation(uint64_t temporalFrameCounter)
		{
			std::mt19937_64 rng(temporalFrameCounter * 0x9E3779B97F4A7C15ull + 0xD1B54A32D192ED03ull);
			std::uniform_real_distribution<float> uniform(0.0f, 1.0f);
			const float u1 = uniform(rng);
			const float u2 = uniform(rng);
			const float u3 = uniform(rng);
			constexpr float twoPi = 6.2831853071795864769f;
			const float a = std::sqrt(std::max(1.0f - u1, 0.0f));
			const float b = std::sqrt(u1);
			// glm::quat component order is (w, x, y, z).
			const glm::quat q(b * std::cos(twoPi * u3),
			                  a * std::sin(twoPi * u2),
			                  a * std::cos(twoPi * u2),
			                  b * std::sin(twoPi * u3));
			return glm::mat3_cast(glm::normalize(q));
		}

		float maxComponent(const glm::vec3& v)
		{
			return std::max(v.x, std::max(v.y, v.z));
		}
	} // namespace

	DDGIRayTracePass::DDGIRayTracePass(GPUDrivenRenderer* renderer)
		: m_renderer(renderer)
	{
	}

	void DDGIRayTracePass::initResources(rhi::Device& device, uint32_t frameCount)
	{
		shutdownResources();

		if (m_renderer == nullptr)
		{
			return;
		}
		const DDGIProbeVolume& probeVolume = m_renderer->getDDGIProbeVolume();
		const GlobalSDFPass* globalSDFPass = m_renderer->getGlobalSDFPass();
		if (!probeVolume.isInitialized() || globalSDFPass == nullptr
			|| globalSDFPass->getVolume().sdfTexture.isNull())
		{
			LOGW("DDGIRayTracePass::initResources skipped: probe volume or global SDF not ready");
			return;
		}

		m_device = &device;
		m_frameCount = std::max(frameCount, 1u);

		// Storage view over the probe volume's radiance scratch texture
		// (x = ray index, y = probe index).
		{
			rhi::TextureViewCreateDesc viewDesc{};
			viewDesc.image = probeVolume.getRadianceBuffer();
			viewDesc.format = rhi::TextureFormat::rgba16Sfloat;
			viewDesc.viewType = rhi::ImageViewType::e2D;
			viewDesc.aspect = rhi::TextureAspect::color;
			viewDesc.baseMipLevel = 0;
			viewDesc.levelCount = 1;
			viewDesc.debugName = "ddgi-raytrace-radiance-view";
			m_radianceView = device.createTextureView(viewDesc);
		}

		// Sampled view over the full Global SDF mip chain so the shader can do
		// the coarse-mip-first query with explicit SampleLevel lods.
		{
			rhi::TextureViewCreateDesc viewDesc{};
			viewDesc.image = globalSDFPass->getVolume().sdfTexture;
			viewDesc.format = rhi::TextureFormat::r16Sfloat;
			viewDesc.viewType = rhi::ImageViewType::e3D;
			viewDesc.aspect = rhi::TextureAspect::color;
			viewDesc.baseMipLevel = 0;
			viewDesc.levelCount = GlobalSDFPass::kMipCount;
			viewDesc.debugName = "ddgi-raytrace-global-sdf-view";
			m_globalSDFView = device.createTextureView(viewDesc);
		}

		// Trilinear within a level, nearest between levels: SampleLevel(uvw, 2)
		// must read exactly the coarse min mip, never blend adjacent levels.
		m_globalSDFSampler = device.createSampler(rhi::SamplerDesc{
			.magFilter = rhi::Filter::linear,
			.minFilter = rhi::Filter::linear,
			.mipmapMode = rhi::MipmapMode::nearest,
			.addressModeU = rhi::AddressMode::clampToEdge,
			.addressModeV = rhi::AddressMode::clampToEdge,
			.addressModeW = rhi::AddressMode::clampToEdge,
			.debugName = "ddgi-raytrace-sdf-sampler",
		});

		const std::array<rhi::ArgumentBinding, 3> bindings{
			{
				rhi::ArgumentBinding{
					.binding = 0, .type = rhi::ArgumentType::storageTexture,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
				rhi::ArgumentBinding{
					.binding = 1, .type = rhi::ArgumentType::combinedImageSampler,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
				rhi::ArgumentBinding{
					.binding = 2, .type = rhi::ArgumentType::uniformBuffer,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
			}
		};
		m_layout = device.createArgumentLayout(rhi::ArgumentLayoutDesc{
			.bindings = bindings.data(),
			.bindingCount = static_cast<uint32_t>(bindings.size()),
			.debugName = "ddgi-raytrace",
		});

		m_tables.resize(m_frameCount);
		m_uniformBuffers.resize(m_frameCount);
		for (uint32_t i = 0; i < m_frameCount; ++i)
		{
			m_uniformBuffers[i] = device.createBuffer(rhi::BufferDesc{
				.size = sizeof(shaderio::DDGIRayTraceUniforms),
				.usage = rhi::BufferUsageFlags::uniform,
				.memoryUsage = rhi::MemoryUsage::cpuToGpu,
				.debugName = "ddgi-raytrace-uniforms",
			});

			m_tables[i] = device.createArgumentTable(m_layout);
			const std::array<rhi::ArgumentWrite, 3> writes{
				{
					rhi::ArgumentWrite{
						.binding = 0, .type = rhi::ArgumentType::storageTexture,
						.textureView = m_radianceView,
						.accessIntent = rhi::ArgumentAccessIntent::readWrite,
					},
					// The SDF volume stays in General layout (written through
					// storage bindings by GlobalSDFPass); readWrite intent keeps
					// the descriptor layout in sync (same as the compose pass).
					rhi::ArgumentWrite{
						.binding = 1, .type = rhi::ArgumentType::combinedImageSampler,
						.textureView = m_globalSDFView,
						.sampler = m_globalSDFSampler,
						.accessIntent = rhi::ArgumentAccessIntent::readWrite,
					},
					rhi::ArgumentWrite{
						.binding = 2, .type = rhi::ArgumentType::uniformBuffer,
						.buffer = m_uniformBuffers[i],
						.size = sizeof(shaderio::DDGIRayTraceUniforms),
					},
				}
			};
			device.updateArgumentTable(m_tables[i], static_cast<uint32_t>(writes.size()), writes.data());
		}

#ifdef USE_SLANG
		const std::array<rhi::ArgumentLayoutHandle, 1> layouts{{m_layout}};
		const rhi::ComputePipelineDesc desc{
			.shaderStage =
			rhi::PipelineShaderStageDesc{
				.stage = rhi::ShaderStage::compute,
				.spirvCode = ddgi_gi_sdf_rays_slang,
				.spirvSize = std::size(ddgi_gi_sdf_rays_slang) * sizeof(uint32_t),
				.entryPoint = "kernelDDGIRayTrace",
			},
			.argumentLayouts = layouts.data(),
			.argumentLayoutCount = static_cast<uint32_t>(layouts.size()),
			.specializationVariant = 0x7404u,
		};
		m_pipeline = device.createComputePipeline(desc);
#endif
	}

	void DDGIRayTracePass::shutdownResources()
	{
		if (m_device == nullptr)
		{
			return;
		}

		if (!m_pipeline.isNull()) m_device->destroyPipeline(m_pipeline);
		m_pipeline = {};

		for (rhi::ArgumentTableHandle& table : m_tables)
		{
			if (!table.isNull()) m_device->destroyArgumentTable(table);
			table = {};
		}
		m_tables.clear();
		for (rhi::BufferHandle& buffer : m_uniformBuffers)
		{
			if (!buffer.isNull()) m_device->destroyBuffer(buffer);
			buffer = {};
		}
		m_uniformBuffers.clear();

		if (!m_layout.isNull()) m_device->destroyArgumentLayout(m_layout);
		m_layout = {};

		if (!m_globalSDFSampler.isNull()) m_device->destroySampler(m_globalSDFSampler);
		m_globalSDFSampler = {};
		if (!m_globalSDFView.isNull()) m_device->destroyTextureView(m_globalSDFView);
		m_globalSDFView = {};
		if (!m_radianceView.isNull()) m_device->destroyTextureView(m_radianceView);
		m_radianceView = {};

		m_radianceLayoutInitialized = false;
		m_frameCount = 0;
		m_device = nullptr;
	}

	PassNode::HandleSlice<PassResourceDependency> DDGIRayTracePass::getDependencies() const
	{
		// The Global SDF write -> compute read hazard is already covered by the
		// final barrier inside GlobalSDFPass::execute; the radiance texture is
		// pass-private until D2-3 and synchronized with internal barriers.
		return {nullptr, 0};
	}

	void DDGIRayTracePass::writeUniforms(uint32_t frameIndex, const PassContext& context) const
	{
		const DDGIProbeVolume& probeVolume = m_renderer->getDDGIProbeVolume();
		const GlobalSDFVolume& volume = m_renderer->getGlobalSDFPass()->getVolume();

		const glm::vec3 extent = volume.worldBoundsMax - volume.worldBoundsMin;
		// Must mirror GlobalSDFPass::writeComposeUniforms (encode convention).
		const float maxEncodeDistance = std::max(maxComponent(extent), 1e-4f);
		const float maxTraceDistance = glm::length(extent);

		// Constraint 4: seed from the monotonic temporal counter, never the
		// frames-in-flight ring index (context.frameIndex).
		const glm::mat3 rotation = makeRandomRotation(m_renderer->getTemporalFrameCounter());

		// Sun light from the frame's directional-light settings; defaults match
		// DirectionalLightSettings if params are unavailable.
		glm::vec3 sunDirection = glm::normalize(glm::vec3(-0.45f, -0.8f, -0.25f));
		glm::vec3 sunColor = glm::vec3(1.0f, 0.95f, 0.85f) * 3.0f;
		if (context.params != nullptr)
		{
			sunDirection = context.params->lightSettings.direction;
			sunColor = context.params->lightSettings.color;
		}
		const float directionLength = glm::length(sunDirection);
		sunDirection = directionLength > 1e-5f ? sunDirection / directionLength
		                                       : glm::vec3(0.0f, -1.0f, 0.0f);

		shaderio::DDGIRayTraceUniforms uniforms{};
		uniforms.rotationCol0 = glm::vec4(rotation[0], 0.0f);
		uniforms.rotationCol1 = glm::vec4(rotation[1], 0.0f);
		uniforms.rotationCol2 = glm::vec4(rotation[2], 0.0f);
		uniforms.volumeBoundsMin = glm::vec4(volume.worldBoundsMin, volume.voxelSize);
		uniforms.volumeBoundsMax = glm::vec4(volume.worldBoundsMax, maxEncodeDistance);
		uniforms.sunDirection = glm::vec4(sunDirection, maxTraceDistance);
		uniforms.sunColor = glm::vec4(sunColor, kDefaultStepScale);
		uniforms.skyColorAlbedo = glm::vec4(kSkyColorR, kSkyColorG, kSkyColorB, kDefaultAlbedo);
		uniforms.probePositionAddress = probeVolume.getProbePositionAddress().value;
		uniforms.raysPerProbe = std::max(probeVolume.getDesc().raysPerProbe, 1u);
		uniforms.totalProbes = probeVolume.getTotalProbes();
		uniforms.maxSteps = kDefaultMaxSteps;
		uniforms.resolution = volume.resolution;

		// cpuToGpu memory is host-coherent on desktop; no explicit flush needed
		// (same contract as GlobalSDFPass's uniform upload).
		void* dst = m_device->mapBuffer(m_uniformBuffers[frameIndex]);
		std::memcpy(dst, &uniforms, sizeof(uniforms));
	}

	void DDGIRayTracePass::execute(const PassContext& context) const
	{
		if (m_renderer == nullptr || context.commandBuffer == nullptr)
		{
			return;
		}
		// DDGI master gate (defaults to false): the default frame is untouched.
		if (!m_renderer->getDDGIConfig().enabled)
		{
			return;
		}
		const DDGIProbeVolume& probeVolume = m_renderer->getDDGIProbeVolume();
		if (m_device == nullptr || m_pipeline.isNull() || m_radianceView.isNull()
			|| !probeVolume.isInitialized() || probeVolume.getTotalProbes() == 0u
			|| !probeVolume.getProbePositionAddress().isValid())
		{
			static bool s_logged = false;
			if (!s_logged)
			{
				LOGW("DDGIRayTracePass skipped: resources not ready (pipeline=%d volume=%d)",
				     m_pipeline.isNull() ? 0 : 1, probeVolume.isInitialized() ? 1 : 0);
				s_logged = true;
			}
			return;
		}
		const uint32_t frameIndex = context.frameIndex;
		if (frameIndex >= m_tables.size() || frameIndex >= m_uniformBuffers.size())
		{
			return;
		}

		writeUniforms(frameIndex, context);

		rhi::CommandBuffer& cmd = *context.commandBuffer;
		cmd.beginEvent("DDGIRayTracePass");

		if (!m_radianceLayoutInitialized)
		{
			const rhi::TextureBarrier initBarrier{
				.texture = probeVolume.getRadianceBuffer(),
				.before = rhi::ResourceState::Undefined,
				.after = rhi::ResourceState::General,
				.range = {
					.aspect = rhi::TextureAspect::color, .baseMipLevel = 0, .levelCount = 1,
					.baseArrayLayer = 0, .layerCount = 1
				},
			};
			cmd.resourceBarrier(&initBarrier, 1, nullptr, 0);
			m_radianceLayoutInitialized = true;
		}

		// dispatchX = ceil(raysPerProbe / 16), dispatchY = totalProbes
		// (LuxGI GISDFRays dispatch shape).
		const uint32_t raysPerProbe = std::max(probeVolume.getDesc().raysPerProbe, 1u);
		const uint32_t groupsX = (raysPerProbe + kGroupSizeX - 1u) / kGroupSizeX;
		const uint32_t groupsY = probeVolume.getTotalProbes();

		cmd.beginEvent("GISDFRays");
		rhi::ComputeEncoder* encoder = cmd.beginComputePass();
		encoder->setPipeline(m_pipeline);
		encoder->setArgumentTable(0, m_tables[frameIndex]);
		encoder->dispatch(rhi::DispatchDesc{groupsX, groupsY, 1u});
		cmd.endEncoding();
		cmd.endEvent();

		// Radiance storage writes -> probe update reads (D2-3) and any later
		// compute consumers of the scratch texture.
		cmd.barrier(rhi::StageFlags::compute, rhi::StageFlags::compute,
		            rhi::HazardFlags::textureWrites);

		cmd.endEvent(); // DDGIRayTracePass
	}
} // namespace demo
