#include "DDGIDebugPass.h"

#include "../DDGIProbeVolume.h"
#include "../GPUDrivenRenderer.h"
#include "../RenderTypes.h"

// Compiled SPIR-V (autogenerated by compile_slang; the shader is flat in
// shaders/ because the CMake glob does not recurse into subdirectories).
#ifdef USE_SLANG
#include "_autogen/ddgi_probe_visualization.slang.h"
#endif

#include <algorithm>
#include <array>
#include <cstring>

namespace demo
{
	DDGIDebugPass::DDGIDebugPass(GPUDrivenRenderer* renderer)
		: m_renderer(renderer)
	{
	}

	void DDGIDebugPass::initResources(rhi::Device& device, uint32_t frameCount)
	{
		shutdownResources();

		if (m_renderer == nullptr)
		{
			return;
		}
		const DDGIProbeVolume& probeVolume = m_renderer->getDDGIProbeVolume();
		if (!probeVolume.isInitialized() || probeVolume.getTotalProbes() == 0u)
		{
			LOGW("DDGIDebugPass::initResources skipped: probe volume not ready");
			return;
		}

		m_device = &device;
		m_frameCount = std::max(frameCount, 1u);

		// Sampled view over the *current* irradiance atlas (D2-3 writes
		// current; same source the lighting SampleProbe path reads).
		{
			rhi::TextureViewCreateDesc viewDesc{};
			viewDesc.image = probeVolume.getIrradianceAtlas();
			viewDesc.format = rhi::TextureFormat::rgba16Sfloat;
			viewDesc.viewType = rhi::ImageViewType::e2D;
			viewDesc.aspect = rhi::TextureAspect::color;
			viewDesc.baseMipLevel = 0;
			viewDesc.levelCount = 1;
			viewDesc.debugName = "ddgi-debug-irradiance-view";
			m_irradianceView = device.createTextureView(viewDesc);
		}

		m_sampler = device.createSampler(rhi::SamplerDesc{
			.magFilter = rhi::Filter::linear,
			.minFilter = rhi::Filter::linear,
			.mipmapMode = rhi::MipmapMode::nearest,
			.addressModeU = rhi::AddressMode::clampToEdge,
			.addressModeV = rhi::AddressMode::clampToEdge,
			.addressModeW = rhi::AddressMode::clampToEdge,
			.debugName = "ddgi-debug-sampler",
		});

		const std::array<rhi::ArgumentBinding, 2> bindings{
			{
				rhi::ArgumentBinding{
					.binding = 0, .type = rhi::ArgumentType::combinedImageSampler,
					.visibility = rhi::ShaderStage::fragment, .arrayCount = 1
				},
				rhi::ArgumentBinding{
					.binding = 1, .type = rhi::ArgumentType::uniformBuffer,
					.visibility = rhi::ShaderStage::allGraphics, .arrayCount = 1
				},
			}
		};
		m_layout = device.createArgumentLayout(rhi::ArgumentLayoutDesc{
			.bindings = bindings.data(),
			.bindingCount = static_cast<uint32_t>(bindings.size()),
			.debugName = "ddgi-debug",
		});

		m_tables.resize(m_frameCount);
		m_uniformBuffers.resize(m_frameCount);
		for (uint32_t i = 0; i < m_frameCount; ++i)
		{
			m_uniformBuffers[i] = device.createBuffer(rhi::BufferDesc{
				.size = sizeof(shaderio::DDGIProbeVisualizationUniforms),
				.usage = rhi::BufferUsageFlags::uniform,
				.memoryUsage = rhi::MemoryUsage::cpuToGpu,
				.debugName = "ddgi-debug-uniforms",
			});

			m_tables[i] = device.createArgumentTable(m_layout);
			const std::array<rhi::ArgumentWrite, 2> writes{
				{
					// The atlas stays in the General layout (the probe update
					// pass writes it as a storage image and never transitions
					// it), so the sampled descriptor uses the readWrite intent
					// -> General layout, same as the lighting-pass binding.
					rhi::ArgumentWrite{
						.binding = 0, .type = rhi::ArgumentType::combinedImageSampler,
						.textureView = m_irradianceView,
						.sampler = m_sampler,
						.accessIntent = rhi::ArgumentAccessIntent::readWrite,
					},
					rhi::ArgumentWrite{
						.binding = 1, .type = rhi::ArgumentType::uniformBuffer,
						.buffer = m_uniformBuffers[i],
						.size = sizeof(shaderio::DDGIProbeVisualizationUniforms),
					},
				}
			};
			device.updateArgumentTable(m_tables[i], static_cast<uint32_t>(writes.size()), writes.data());
		}

#ifdef USE_SLANG
		const std::array<rhi::PipelineShaderStageDesc, 2> stages{
			{
				rhi::PipelineShaderStageDesc{
					.stage = rhi::ShaderStage::vertex,
					.spirvCode = ddgi_probe_visualization_slang,
					.spirvSize = std::size(ddgi_probe_visualization_slang) * sizeof(uint32_t),
					.entryPoint = "vertexProbeVisMain"
				},
				rhi::PipelineShaderStageDesc{
					.stage = rhi::ShaderStage::fragment,
					.spirvCode = ddgi_probe_visualization_slang,
					.spirvSize = std::size(ddgi_probe_visualization_slang) * sizeof(uint32_t),
					.entryPoint = "fragmentProbeVisMain"
				},
			}
		};
		const std::array<rhi::DynamicState, 2> dynamicStates{
			{
				rhi::DynamicState::viewport,
				rhi::DynamicState::scissor,
			}
		};
		const std::array<rhi::BlendAttachmentState, 1> blendStates{
			{
				rhi::BlendAttachmentState{.blendEnable = false, .colorWriteMask = rhi::ColorComponentFlags::all},
			}
		};
		const std::array<rhi::TextureFormat, 1> colorFormats{{m_renderer->getSceneColorHdrFormat()}};
		const std::array<rhi::ArgumentLayoutHandle, 1> layouts{{m_layout}};
		rhi::GraphicsPipelineDesc desc{
			.shaderStages = stages.data(),
			.shaderStageCount = static_cast<uint32_t>(stages.size()),
			.vertexInput = rhi::VertexInputLayoutDesc{}, // buffer-less procedural sphere
			.rasterState = rhi::RasterState{},
			// Depth test on / write off against the scene depth (reversed-Z:
			// greaterOrEqual, matching the engine's geometry passes).
			.depthState = rhi::DepthState{true, false, rhi::CompareOp::greaterOrEqual},
			.blendStates = blendStates.data(),
			.blendStateCount = static_cast<uint32_t>(blendStates.size()),
			.dynamicStates = dynamicStates.data(),
			.dynamicStateCount = static_cast<uint32_t>(dynamicStates.size()),
			.renderingInfo =
			{
				.colorFormats = colorFormats.data(),
				.colorFormatCount = static_cast<uint32_t>(colorFormats.size()),
				.depthFormat = m_renderer->getSceneDepthFormat(),
			},
			.argumentLayouts = layouts.data(),
			.argumentLayoutCount = static_cast<uint32_t>(layouts.size()),
			.specializationVariant = 0x7409u,
		};
		desc.rasterState.topology = rhi::PrimitiveTopology::triangleList;
		desc.rasterState.cullMode = rhi::CullMode::none;
		desc.rasterState.frontFace = rhi::FrontFace::counterClockwise;
		desc.rasterState.sampleCount = rhi::SampleCount::count1;
		m_pipeline = device.createGraphicsPipeline(desc);
#endif
	}

	void DDGIDebugPass::shutdownResources()
	{
		if (m_device == nullptr)
		{
			return;
		}

		if (!m_pipeline.isNull()) m_device->destroyPipeline(m_pipeline);
		m_pipeline = {};

		for (rhi::ArgumentTableHandle& table : m_tables)
		{
			if (!table.isNull()) m_device->destroyArgumentTable(table);
			table = {};
		}
		m_tables.clear();
		for (rhi::BufferHandle& buffer : m_uniformBuffers)
		{
			if (!buffer.isNull()) m_device->destroyBuffer(buffer);
			buffer = {};
		}
		m_uniformBuffers.clear();

		if (!m_layout.isNull()) m_device->destroyArgumentLayout(m_layout);
		m_layout = {};

		if (!m_sampler.isNull()) m_device->destroySampler(m_sampler);
		m_sampler = {};
		if (!m_irradianceView.isNull()) m_device->destroyTextureView(m_irradianceView);
		m_irradianceView = {};

		m_frameCount = 0;
		m_device = nullptr;
	}

	PassNode::HandleSlice<PassResourceDependency> DDGIDebugPass::getDependencies() const
	{
		// Same attachment contract as the skybox overlay: HDR color as a
		// load/store attachment, scene depth read-only for the depth test.
		// The probe-update -> fragment-sample hazard on the irradiance atlas
		// is covered by DDGIProbeUpdatePass's trailing
		// compute -> compute|fragment barrier (Wave D3-1).
		static const std::array<PassResourceDependency, 2> dependencies = {
			PassResourceDependency::texture(kPassSceneColorHdrHandle, ResourceAccess::readWrite,
			                                rhi::ShaderStage::fragment,
			                                rhi::ResourceState::ColorAttachment),
			PassResourceDependency::texture(kPassSceneDepthHandle, ResourceAccess::read, rhi::ShaderStage::fragment,
			                                rhi::ResourceState::DepthStencilReadOnly),
		};
		return {dependencies.data(), static_cast<uint32_t>(dependencies.size())};
	}

	void DDGIDebugPass::writeUniforms(uint32_t frameIndex, const PassContext& context) const
	{
		const DDGIProbeVolume& probeVolume = m_renderer->getDDGIProbeVolume();
		const DDGIConfig& config = m_renderer->getDDGIConfig();
		const rhi::Extent2D atlasExtent = probeVolume.getIrradianceAtlasExtent();

		shaderio::DDGIProbeVisualizationUniforms uniforms{};
		// Jittered VP: the spheres must match the jittered scene depth buffer
		// they are tested against (TAA resolves the jitter afterwards).
		uniforms.viewProjection = context.params->cameraUniforms->viewProjection;
		uniforms.probePositionAddress = probeVolume.getProbePositionAddress().value;
		uniforms.totalProbes = probeVolume.getTotalProbes();
		uniforms.irradianceAtlasWidth = atlasExtent.width;
		uniforms.irradianceAtlasHeight = atlasExtent.height;
		uniforms.irradianceSideLength = probeVolume.getDesc().irradianceTexelSize;
		uniforms.probeRadius = kProbeRadius;
		uniforms.ddgiGamma = config.ddgiGamma;

		// cpuToGpu memory is host-coherent on desktop; no explicit flush needed
		// (same contract as DDGIRayTracePass's uniform upload).
		void* dst = m_device->mapBuffer(m_uniformBuffers[frameIndex]);
		std::memcpy(dst, &uniforms, sizeof(uniforms));
	}

	void DDGIDebugPass::execute(const PassContext& context) const
	{
		if (m_renderer == nullptr || context.commandBuffer == nullptr || context.params == nullptr)
		{
			return;
		}
		// Double gate: DDGI master toggle AND the ImGui visualize checkbox
		// (both default false) — the default frame stays untouched.
		if (!m_renderer->getDDGIConfig().enabled || !context.params->debugOptions.ddgiDebugVisualize)
		{
			return;
		}
		const DDGIProbeVolume& probeVolume = m_renderer->getDDGIProbeVolume();
		if (m_device == nullptr || m_pipeline.isNull() || m_irradianceView.isNull()
			|| !probeVolume.isInitialized() || probeVolume.getTotalProbes() == 0u
			|| !probeVolume.getProbePositionAddress().isValid()
			|| context.params->cameraUniforms == nullptr)
		{
			return;
		}
		const uint32_t frameIndex = context.frameIndex;
		if (frameIndex >= m_tables.size() || frameIndex >= m_uniformBuffers.size())
		{
			return;
		}

		const GPUDrivenRenderer::ScreenPassTargets targets = m_renderer->getScreenColorDepthTargets();
		if (!targets.valid)
		{
			return;
		}

		writeUniforms(frameIndex, context);

		context.commandBuffer->beginEvent("DDGIDebugPass");

		const rhi::RenderTargetDesc colorTarget{
			.texture = {},
			.view = targets.colorView,
			.state = rhi::ResourceState::ColorAttachment,
			.loadOp = rhi::LoadOp::load,
			.storeOp = rhi::StoreOp::store,
		};
		const rhi::DepthTargetDesc depthTarget{
			.texture = {},
			.view = targets.depthView,
			.state = rhi::ResourceState::DepthStencilReadOnly,
			.loadOp = rhi::LoadOp::load,
			.storeOp = rhi::StoreOp::store,
			.clearValue = {0.0f, 0},
		};

		rhi::RenderEncoder* enc = context.commandBuffer->beginRenderPass(rhi::RenderPassDesc{
			.renderArea = {{0, 0}, targets.extent},
			.colorTargets = &colorTarget,
			.colorTargetCount = 1,
			.depthTarget = &depthTarget,
		});
		enc->setViewport(rhi::Viewport{
			0.0f, 0.0f, static_cast<float>(targets.extent.width),
			static_cast<float>(targets.extent.height), 0.0f, 1.0f
		});
		enc->setScissor(rhi::Rect2D{{0, 0}, targets.extent});

		enc->setPipeline(m_pipeline);
		enc->setArgumentTable(rhi::ShaderStage::allGraphics, 0, m_tables[frameIndex]);

		// Procedural UV sphere: stacks * slices * 6 vertices per instance,
		// one instance per probe (instance id == probe index in the shader).
		constexpr uint32_t kSphereVertexCount =
			static_cast<uint32_t>(shaderio::LDDGIProbeVisStacks * shaderio::LDDGIProbeVisSlices * 6);
		enc->draw(rhi::DrawDesc{
			.vertexCount = kSphereVertexCount,
			.instanceCount = probeVolume.getTotalProbes(),
			.firstVertex = 0,
			.firstInstance = 0
		});

		context.commandBuffer->endEncoding();
		context.commandBuffer->endEvent();
	}
} // namespace demo
