#include "GlobalSDFPass.h"

#include "../ArgumentTables.h"
#include "../GPUDrivenRenderer.h"

// Compiled SPIR-V for the global SDF compute shaders (autogenerated by
// compile_slang; shaders are flat in shaders/ because the CMake glob does not
// recurse into subdirectories).
#ifdef USE_SLANG
#include "_autogen/sdf_global_clear.slang.h"
#include "_autogen/sdf_global_compose.slang.h"
#include "_autogen/sdf_global_mipmap.slang.h"
#endif

#include <algorithm>
#include <array>
#include <cstring>

namespace demo
{
	static_assert(GlobalSDFPass::kMipCount == static_cast<uint32_t>(shaderio::LGlobalSDFMipCount),
	              "GlobalSDFPass::kMipCount must match shaderio::LGlobalSDFMipCount");
	static_assert((GlobalSDFPass::kResolution >> (GlobalSDFPass::kMipCount - 1u)) >= 1u,
	              "Global SDF mip chain underflows the base resolution");

	namespace
	{
		constexpr uint32_t kMaxMeshSDFs = static_cast<uint32_t>(shaderio::LGlobalSDFMaxMeshSDFs);
		constexpr uint32_t kGroupSize = 4u; // matches [numthreads(4, 4, 4)] in the shaders

		uint32_t dispatchGroups(uint32_t resolution)
		{
			return (resolution + kGroupSize - 1u) / kGroupSize;
		}

		float maxComponent(const glm::vec3& v)
		{
			return std::max(v.x, std::max(v.y, v.z));
		}
	} // namespace

	GlobalSDFPass::GlobalSDFPass(GPUDrivenRenderer* renderer)
		: m_renderer(renderer)
	{
	}

	void GlobalSDFPass::initResources(rhi::Device& device, uint32_t frameCount)
	{
		shutdownResources();

		m_device = &device;
		m_frameCount = std::max(frameCount, 1u);

		m_volume.resolution = kResolution;
		m_volume.worldBoundsMin = glm::vec3(-kDefaultHalfExtent);
		m_volume.worldBoundsMax = glm::vec3(kDefaultHalfExtent);
		m_volume.voxelSize = (2.0f * kDefaultHalfExtent) / static_cast<float>(kResolution);

		m_volume.sdfTexture = device.createTexture(rhi::TextureDesc{
			.dimension = rhi::TextureDimension::e3D,
			.format = rhi::TextureFormat::r16Sfloat,
			.usage = rhi::TextureUsageFlags::sampled | rhi::TextureUsageFlags::storage,
			.extent = {kResolution, kResolution, kResolution},
			.mipLevels = kMipCount,
			.arrayLayers = 1,
			.sampleCount = rhi::SampleCount::count1,
			.memoryUsage = rhi::MemoryUsage::gpuOnly,
			.debugName = "global-sdf-volume",
		});

		m_volume.mipViews.resize(kMipCount);
		for (uint32_t mip = 0; mip < kMipCount; ++mip)
		{
			rhi::TextureViewCreateDesc viewDesc{};
			viewDesc.image = m_volume.sdfTexture;
			viewDesc.format = rhi::TextureFormat::r16Sfloat;
			viewDesc.viewType = rhi::ImageViewType::e3D;
			viewDesc.aspect = rhi::TextureAspect::color;
			viewDesc.baseMipLevel = mip;
			viewDesc.levelCount = 1;
			viewDesc.debugName = "global-sdf-volume-mip";
			m_volume.mipViews[mip] = device.createTextureView(viewDesc);
		}

		m_meshSDFSampler = device.createSampler(rhi::SamplerDesc{
			.magFilter = rhi::Filter::linear,
			.minFilter = rhi::Filter::linear,
			.mipmapMode = rhi::MipmapMode::nearest,
			.addressModeU = rhi::AddressMode::clampToEdge,
			.addressModeV = rhi::AddressMode::clampToEdge,
			.addressModeW = rhi::AddressMode::clampToEdge,
			.debugName = "global-sdf-mesh-sampler",
		});

		// --- Argument layouts ---
		const std::array<rhi::ArgumentBinding, 1> clearBindings{
			{
				rhi::ArgumentBinding{
					.binding = 0, .type = rhi::ArgumentType::storageTexture,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
			}
		};
		m_clearLayout = device.createArgumentLayout(rhi::ArgumentLayoutDesc{
			.bindings = clearBindings.data(),
			.bindingCount = static_cast<uint32_t>(clearBindings.size()),
			.debugName = "global-sdf-clear",
		});

		const std::array<rhi::ArgumentBinding, 3> composeBindings{
			{
				rhi::ArgumentBinding{
					.binding = 0, .type = rhi::ArgumentType::storageTexture,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
				rhi::ArgumentBinding{
					.binding = 1, .type = rhi::ArgumentType::combinedImageSampler,
					.visibility = rhi::ShaderStage::compute, .arrayCount = kMaxMeshSDFs
				},
				rhi::ArgumentBinding{
					.binding = 2, .type = rhi::ArgumentType::uniformBuffer,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
			}
		};
		m_composeLayout = device.createArgumentLayout(rhi::ArgumentLayoutDesc{
			.bindings = composeBindings.data(),
			.bindingCount = static_cast<uint32_t>(composeBindings.size()),
			.debugName = "global-sdf-compose",
		});

		const std::array<rhi::ArgumentBinding, 2> mipmapBindings{
			{
				rhi::ArgumentBinding{
					.binding = 0, .type = rhi::ArgumentType::sampledTexture,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
				rhi::ArgumentBinding{
					.binding = 1, .type = rhi::ArgumentType::storageTexture,
					.visibility = rhi::ShaderStage::compute, .arrayCount = 1
				},
			}
		};
		m_mipmapLayout = device.createArgumentLayout(rhi::ArgumentLayoutDesc{
			.bindings = mipmapBindings.data(),
			.bindingCount = static_cast<uint32_t>(mipmapBindings.size()),
			.debugName = "global-sdf-mipmap",
		});

		// --- Argument tables ---
		m_clearTable = device.createArgumentTable(m_clearLayout);
		{
			const rhi::ArgumentWrite clearWrite{
				.binding = 0, .type = rhi::ArgumentType::storageTexture,
				.textureView = m_volume.mipViews[0],
				.accessIntent = rhi::ArgumentAccessIntent::readWrite,
			};
			device.updateArgumentTable(m_clearTable, 1, &clearWrite);
		}

		m_mipmapTables.resize(kMipCount - 1u);
		for (uint32_t mip = 1; mip < kMipCount; ++mip)
		{
			m_mipmapTables[mip - 1u] = device.createArgumentTable(m_mipmapLayout);
			const std::array<rhi::ArgumentWrite, 2> mipWrites{
				{
					// Source mip stays in General layout (written via storage
					// bindings); readWrite intent keeps the descriptor layout in sync.
					rhi::ArgumentWrite{
						.binding = 0, .type = rhi::ArgumentType::sampledTexture,
						.textureView = m_volume.mipViews[mip - 1u],
						.accessIntent = rhi::ArgumentAccessIntent::readWrite,
					},
					rhi::ArgumentWrite{
						.binding = 1, .type = rhi::ArgumentType::storageTexture,
						.textureView = m_volume.mipViews[mip],
						.accessIntent = rhi::ArgumentAccessIntent::readWrite,
					},
				}
			};
			device.updateArgumentTable(m_mipmapTables[mip - 1u],
			                           static_cast<uint32_t>(mipWrites.size()), mipWrites.data());
		}

		m_composeTables.resize(m_frameCount);
		m_composeUniformBuffers.resize(m_frameCount);
		for (uint32_t i = 0; i < m_frameCount; ++i)
		{
			m_composeTables[i] = device.createArgumentTable(m_composeLayout);
			m_composeUniformBuffers[i] = device.createBuffer(rhi::BufferDesc{
				.size = sizeof(shaderio::GlobalSDFComposeUniforms),
				.usage = rhi::BufferUsageFlags::uniform,
				.memoryUsage = rhi::MemoryUsage::cpuToGpu,
				.debugName = "global-sdf-compose-uniforms",
			});
		}

		// --- Pipelines ---
#ifdef USE_SLANG
		const auto createPipeline = [&](const uint32_t* spirv, size_t wordCount, const char* entryPoint,
		                                rhi::ArgumentLayoutHandle layout, uint32_t pushSize, uint32_t variant)
		{
			const std::array<rhi::ArgumentLayoutHandle, 1> layouts{{layout}};
			const std::array<rhi::PipelinePushConstantRange, 1> pushRanges{
				{
					rhi::PipelinePushConstantRange{
						.stages = rhi::ShaderStage::compute, .offset = 0, .size = pushSize
					},
				}
			};
			const rhi::ComputePipelineDesc desc{
				.shaderStage =
				rhi::PipelineShaderStageDesc{
					.stage = rhi::ShaderStage::compute,
					.spirvCode = spirv,
					.spirvSize = wordCount * sizeof(uint32_t),
					.entryPoint = entryPoint,
				},
				.argumentLayouts = layouts.data(),
				.argumentLayoutCount = static_cast<uint32_t>(layouts.size()),
				.pushConstantRanges = pushSize > 0u ? pushRanges.data() : nullptr,
				.pushConstantRangeCount = pushSize > 0u ? static_cast<uint32_t>(pushRanges.size()) : 0u,
				.specializationVariant = variant,
			};
			return device.createComputePipeline(desc);
		};

		m_clearPipeline = createPipeline(sdf_global_clear_slang, std::size(sdf_global_clear_slang),
		                                 "kernelGlobalSDFClear", m_clearLayout,
		                                 sizeof(shaderio::GlobalSDFDispatchPush), 0x7401u);
		m_composePipeline = createPipeline(sdf_global_compose_slang, std::size(sdf_global_compose_slang),
		                                   "kernelGlobalSDFCompose", m_composeLayout, 0u, 0x7402u);
		m_mipmapPipeline = createPipeline(sdf_global_mipmap_slang, std::size(sdf_global_mipmap_slang),
		                                  "kernelGlobalSDFMipmap", m_mipmapLayout,
		                                  sizeof(shaderio::GlobalSDFDispatchPush), 0x7403u);
#endif
	}

	void GlobalSDFPass::shutdownResources()
	{
		if (m_device == nullptr)
		{
			return;
		}

		destroyMeshViews();
		m_meshEntries.clear();

		if (!m_clearPipeline.isNull()) m_device->destroyPipeline(m_clearPipeline);
		if (!m_composePipeline.isNull()) m_device->destroyPipeline(m_composePipeline);
		if (!m_mipmapPipeline.isNull()) m_device->destroyPipeline(m_mipmapPipeline);
		m_clearPipeline = {};
		m_composePipeline = {};
		m_mipmapPipeline = {};

		if (!m_clearTable.isNull()) m_device->destroyArgumentTable(m_clearTable);
		m_clearTable = {};
		for (rhi::ArgumentTableHandle& table : m_mipmapTables)
		{
			if (!table.isNull()) m_device->destroyArgumentTable(table);
			table = {};
		}
		m_mipmapTables.clear();
		for (rhi::ArgumentTableHandle& table : m_composeTables)
		{
			if (!table.isNull()) m_device->destroyArgumentTable(table);
			table = {};
		}
		m_composeTables.clear();
		for (rhi::BufferHandle& buffer : m_composeUniformBuffers)
		{
			if (!buffer.isNull()) m_device->destroyBuffer(buffer);
			buffer = {};
		}
		m_composeUniformBuffers.clear();

		if (!m_clearLayout.isNull()) m_device->destroyArgumentLayout(m_clearLayout);
		if (!m_composeLayout.isNull()) m_device->destroyArgumentLayout(m_composeLayout);
		if (!m_mipmapLayout.isNull()) m_device->destroyArgumentLayout(m_mipmapLayout);
		m_clearLayout = {};
		m_composeLayout = {};
		m_mipmapLayout = {};

		if (!m_meshSDFSampler.isNull()) m_device->destroySampler(m_meshSDFSampler);
		m_meshSDFSampler = {};

		for (rhi::TextureViewHandle& view : m_volume.mipViews)
		{
			if (!view.isNull()) m_device->destroyTextureView(view);
			view = {};
		}
		m_volume.mipViews.clear();
		if (!m_volume.sdfTexture.isNull()) m_device->destroyTexture(m_volume.sdfTexture);
		m_volume = {};

		m_layoutInitialized = false;
		m_frameCount = 0;
		m_device = nullptr;
	}

	void GlobalSDFPass::setMeshSDFList(const GlobalSDFMeshEntry* entries, uint32_t count)
	{
		destroyMeshViews();
		m_meshEntries.clear();

		if (entries == nullptr || count == 0u)
		{
			return;
		}
		if (m_device == nullptr)
		{
			LOGW("GlobalSDFPass::setMeshSDFList called before initResources; list ignored");
			return;
		}

		const uint32_t clamped = std::min(count, kMaxMeshSDFs);
		if (clamped < count)
		{
			LOGW("GlobalSDFPass: mesh SDF list truncated from %u to %u entries", count, clamped);
		}

		m_meshEntries.reserve(clamped);
		m_meshViews.reserve(clamped);
		for (uint32_t i = 0; i < clamped; ++i)
		{
			if (entries[i].sdfTexture.isNull())
			{
				continue;
			}
			rhi::TextureViewCreateDesc viewDesc{};
			viewDesc.image = entries[i].sdfTexture;
			viewDesc.format = rhi::TextureFormat::r16Sfloat;
			viewDesc.viewType = rhi::ImageViewType::e3D;
			viewDesc.aspect = rhi::TextureAspect::color;
			viewDesc.baseMipLevel = 0;
			viewDesc.levelCount = 1;
			viewDesc.debugName = "global-sdf-mesh-view";
			m_meshViews.push_back(m_device->createTextureView(viewDesc));
			m_meshEntries.push_back(entries[i]);
		}
	}

	void GlobalSDFPass::destroyMeshViews()
	{
		if (m_device != nullptr)
		{
			for (rhi::TextureViewHandle view : m_meshViews)
			{
				if (!view.isNull()) m_device->destroyTextureView(view);
			}
		}
		m_meshViews.clear();
	}

	PassNode::HandleSlice<PassResourceDependency> GlobalSDFPass::getDependencies() const
	{
		// All resources are pass-private: created here and synchronized with
		// internal barriers; nothing is exposed to the executor graph yet.
		return {nullptr, 0};
	}

	void GlobalSDFPass::writeComposeUniforms(uint32_t frameIndex, uint32_t meshCount) const
	{
		shaderio::GlobalSDFComposeUniforms uniforms{};
		const glm::vec3 extent = m_volume.worldBoundsMax - m_volume.worldBoundsMin;
		const float globalMaxDistance = std::max(maxComponent(extent), 1e-4f);
		uniforms.volumeBoundsMin = glm::vec4(m_volume.worldBoundsMin, m_volume.voxelSize);
		uniforms.volumeBoundsMax = glm::vec4(m_volume.worldBoundsMax, globalMaxDistance);
		uniforms.resolution = m_volume.resolution;
		uniforms.numMeshSDFs = meshCount;
		for (uint32_t i = 0; i < meshCount; ++i)
		{
			const GlobalSDFMeshEntry& entry = m_meshEntries[i];
			// Mesh max encode distance mirrors the sdf_baker convention:
			// max edge length of the padded mesh AABB.
			const float meshMaxDistance = std::max(maxComponent(entry.boundsMax - entry.boundsMin), 1e-4f);
			uniforms.meshBoundsMin[i] = glm::vec4(entry.boundsMin, 0.0f);
			uniforms.meshBoundsMax[i] = glm::vec4(entry.boundsMax, meshMaxDistance);
		}

		// cpuToGpu memory is host-coherent on desktop; no explicit flush needed
		// (same contract as HiZDepthPyramid's uniform upload).
		void* dst = m_device->mapBuffer(m_composeUniformBuffers[frameIndex]);
		std::memcpy(dst, &uniforms, sizeof(uniforms));
	}

	void GlobalSDFPass::updateComposeArgumentTable(uint32_t frameIndex, uint32_t meshCount) const
	{
		std::array<rhi::ArgumentWrite, kMaxMeshSDFs + 2u> writes{};
		uint32_t writeCount = 0;
		writes[writeCount++] = rhi::ArgumentWrite{
			.binding = 0, .type = rhi::ArgumentType::storageTexture,
			.textureView = m_volume.mipViews[0],
			.accessIntent = rhi::ArgumentAccessIntent::readWrite,
		};
		for (uint32_t i = 0; i < kMaxMeshSDFs; ++i)
		{
			// Unused slots repeat the last valid view (HiZ depth pyramid pattern)
			// so every descriptor in the fixed-size array is written. Mesh SDF
			// textures stay in General layout after the SDFLoader upload, hence
			// the readWrite intent.
			const uint32_t sourceIndex = std::min(i, meshCount - 1u);
			writes[writeCount++] = rhi::ArgumentWrite{
				.binding = 1, .arrayElement = i,
				.type = rhi::ArgumentType::combinedImageSampler,
				.textureView = m_meshViews[sourceIndex],
				.sampler = m_meshSDFSampler,
				.accessIntent = rhi::ArgumentAccessIntent::readWrite,
			};
		}
		writes[writeCount++] = rhi::ArgumentWrite{
			.binding = 2, .type = rhi::ArgumentType::uniformBuffer,
			.buffer = m_composeUniformBuffers[frameIndex],
			.size = sizeof(shaderio::GlobalSDFComposeUniforms),
		};
		m_device->updateArgumentTable(m_composeTables[frameIndex], writeCount, writes.data());
	}

	void GlobalSDFPass::execute(const PassContext& context) const
	{
		if (m_renderer == nullptr || context.commandBuffer == nullptr)
		{
			return;
		}
		// DDGI master gate (defaults to false): the default frame is untouched.
		if (!m_renderer->getDDGIConfig().enabled)
		{
			return;
		}
		if (m_device == nullptr || m_volume.sdfTexture.isNull() || m_clearTable.isNull()
			|| m_clearPipeline.isNull() || m_composePipeline.isNull() || m_mipmapPipeline.isNull()
			|| m_mipmapTables.size() != kMipCount - 1u)
		{
			static bool s_logged = false;
			if (!s_logged)
			{
				LOGW("GlobalSDFPass skipped: resources not ready (texture=%d clear=%d compose=%d mipmap=%d)",
				     m_volume.sdfTexture.isNull() ? 0 : 1, m_clearPipeline.isNull() ? 0 : 1,
				     m_composePipeline.isNull() ? 0 : 1, m_mipmapPipeline.isNull() ? 0 : 1);
				s_logged = true;
			}
			return;
		}

		rhi::CommandBuffer& cmd = *context.commandBuffer;
		cmd.beginEvent("GlobalSDFPass");

		if (!m_layoutInitialized)
		{
			const rhi::TextureBarrier initBarrier{
				.texture = m_volume.sdfTexture,
				.before = rhi::ResourceState::Undefined,
				.after = rhi::ResourceState::General,
				.range = {
					.aspect = rhi::TextureAspect::color, .baseMipLevel = 0, .levelCount = kMipCount,
					.baseArrayLayer = 0, .layerCount = 1
				},
			};
			cmd.resourceBarrier(&initBarrier, 1, nullptr, 0);
			m_layoutInitialized = true;
		}

		const uint32_t baseGroups = dispatchGroups(m_volume.resolution);

		// --- Clear: write the max normalized distance (1.0) into mip 0 ---
		{
			const shaderio::GlobalSDFDispatchPush clearPush{
				.params0 = glm::vec4(static_cast<float>(m_volume.resolution), 1.0f, 0.0f, 0.0f),
			};
			cmd.beginEvent("GlobalSDFClear");
			rhi::ComputeEncoder* clear = cmd.beginComputePass();
			clear->setPipeline(m_clearPipeline);
			clear->setArgumentTable(0, m_clearTable);
			clear->setRootConstants(kPrimaryRootConstantsSlot, &clearPush, sizeof(clearPush));
			clear->dispatch(rhi::DispatchDesc{baseGroups, baseGroups, baseGroups});
			cmd.endEncoding();
			cmd.endEvent();
		}
		// Same-pass barrier: clear writes mip 0 consumed by compose/mipmap below.
		cmd.barrier(rhi::StageFlags::compute, rhi::StageFlags::compute, rhi::HazardFlags::textureWrites);

		// --- Compose: min over the registered mesh SDF list ---
		// Empty list (this wave): early-out, the volume stays at max distance.
		const uint32_t meshCount = std::min(static_cast<uint32_t>(m_meshViews.size()), kMaxMeshSDFs);
		const uint32_t frameIndex = context.frameIndex;
		if (meshCount > 0u && frameIndex < m_composeTables.size()
			&& frameIndex < m_composeUniformBuffers.size())
		{
			writeComposeUniforms(frameIndex, meshCount);
			updateComposeArgumentTable(frameIndex, meshCount);

			cmd.beginEvent("GlobalSDFCompose");
			rhi::ComputeEncoder* compose = cmd.beginComputePass();
			compose->setPipeline(m_composePipeline);
			compose->setArgumentTable(0, m_composeTables[frameIndex]);
			compose->dispatch(rhi::DispatchDesc{baseGroups, baseGroups, baseGroups});
			cmd.endEncoding();
			cmd.endEvent();

			cmd.barrier(rhi::StageFlags::compute, rhi::StageFlags::compute, rhi::HazardFlags::textureWrites);
		}

		// --- Mipmap: per-level 2x2x2 min downsample ---
		cmd.beginEvent("GlobalSDFMipmap");
		for (uint32_t mip = 1; mip < kMipCount; ++mip)
		{
			const uint32_t dstResolution = std::max(1u, m_volume.resolution >> mip);
			const shaderio::GlobalSDFDispatchPush mipPush{
				.params0 = glm::vec4(static_cast<float>(dstResolution), 0.0f, 0.0f, 0.0f),
			};
			const uint32_t mipGroups = dispatchGroups(dstResolution);

			rhi::ComputeEncoder* mipmap = cmd.beginComputePass();
			mipmap->setPipeline(m_mipmapPipeline);
			mipmap->setArgumentTable(0, m_mipmapTables[mip - 1u]);
			mipmap->setRootConstants(kPrimaryRootConstantsSlot, &mipPush, sizeof(mipPush));
			mipmap->dispatch(rhi::DispatchDesc{mipGroups, mipGroups, mipGroups});
			cmd.endEncoding();

			// Level N feeds level N+1; the final iteration also covers future
			// compute/fragment consumers of the finished volume.
			cmd.barrier(rhi::StageFlags::compute,
			            rhi::StageFlags::compute | rhi::StageFlags::fragmentShader,
			            rhi::HazardFlags::textureWrites);
		}
		cmd.endEvent();

		cmd.endEvent(); // GlobalSDFPass
	}
} // namespace demo
