#include "IBLResources.h"
#include "../rhi/RHICommandBuffer.h"

// Compiled SPIR-V for the IBL generation compute shaders (autogenerated, Slang).
#ifdef USE_SLANG
#include "_autogen/shader.ibl_dfg.slang.h"
#include "_autogen/shader.ibl_irradiance.slang.h"
#include "_autogen/shader.ibl_prefilter.slang.h"
#endif

#include <algorithm>
#include <array>
#include <cmath>

namespace demo
{
	namespace
	{
		void imageBarrier(rhi::CommandBuffer& cmd,
		                  rhi::TextureHandle image,
		                  const rhi::TextureSubresourceRange& range,
		                  rhi::ResourceState before,
		                  rhi::ResourceState after)
		{
			const rhi::TextureBarrier barrier{
				.texture = image,
				.before = before,
				.after = after,
				.range = range,
			};
			cmd.resourceBarrier(&barrier, 1, nullptr, 0);
		}

		rhi::TextureSubresourceRange colorRange(uint32_t mipCount, uint32_t layerCount)
		{
			return rhi::TextureSubresourceRange{
				.aspect = rhi::TextureAspect::color,
				.baseMipLevel = 0,
				.levelCount = mipCount,
				.baseArrayLayer = 0,
				.layerCount = layerCount,
			};
		}
	} // namespace

	void IBLResources::init(rhi::Device& device, rhi::CommandBuffer& rhiCmd, const CreateInfo& createInfo)
	{
		deinit();
		m_rhiDevice = &device;
		m_cubeMapSize = createInfo.cubeMapSize;
		m_dfgLUTSize = createInfo.dfgLUTSize;

		m_cubeMapSampler = m_rhiDevice->createSampler(rhi::SamplerDesc{
			.magFilter = rhi::Filter::linear,
			.minFilter = rhi::Filter::linear,
			.mipmapMode = rhi::MipmapMode::linear,
			.addressModeU = rhi::AddressMode::clampToEdge,
			.addressModeV = rhi::AddressMode::clampToEdge,
			.addressModeW = rhi::AddressMode::clampToEdge,
			.debugName = "IBL_CubeMapSampler",
		});
		m_lutSampler = m_rhiDevice->createSampler(rhi::SamplerDesc{
			.magFilter = rhi::Filter::linear,
			.minFilter = rhi::Filter::linear,
			.addressModeU = rhi::AddressMode::clampToEdge,
			.addressModeV = rhi::AddressMode::clampToEdge,
			.addressModeW = rhi::AddressMode::clampToEdge,
			.debugName = "IBL_LUTSampler",
		});

		createImages(rhiCmd, createInfo);
		generateIBLMaps(rhiCmd, createInfo);
		transitionGeneratedImagesForSampling(rhiCmd);
	}

	void IBLResources::createImages(rhi::CommandBuffer& rhiCmd, const CreateInfo& createInfo)
	{
		m_maxMipLevel = static_cast<uint32_t>(std::floor(std::log2(std::max(createInfo.cubeMapSize, 1u))));

		const auto makeView = [&](rhi::TextureHandle imageHandle, rhi::TextureFormat format,
		                          rhi::ImageViewType viewType, uint32_t levelCount,
		                          uint32_t layerCount) -> rhi::TextureViewHandle
		{
			rhi::TextureViewCreateDesc desc{};
			desc.image = imageHandle;
			desc.format = format;
			desc.viewType = viewType;
			desc.aspect = rhi::TextureAspect::color;
			desc.levelCount = levelCount;
			desc.layerCount = layerCount;
			return m_rhiDevice->createTextureView(desc);
		};

		const rhi::TextureUsageFlags storageUsage = rhi::TextureUsageFlags::sampled |
			rhi::TextureUsageFlags::storage | rhi::TextureUsageFlags::transferDst;

		m_prefilteredMap = m_rhiDevice->createTexture(rhi::TextureDesc{
			.dimension = rhi::TextureDimension::eCube,
			.format = createInfo.cubeMapFormat,
			.usage = storageUsage,
			.extent = {createInfo.cubeMapSize, createInfo.cubeMapSize, 1},
			.mipLevels = m_maxMipLevel + 1,
			.arrayLayers = 6,
			.debugName = "IBL_PrefilteredMap",
		});
		m_prefilteredMapView = makeView(m_prefilteredMap, createInfo.cubeMapFormat, rhi::ImageViewType::eCube,
		                                m_maxMipLevel + 1, 6);

		m_irradianceMap = m_rhiDevice->createTexture(rhi::TextureDesc{
			.dimension = rhi::TextureDimension::eCube,
			.format = createInfo.cubeMapFormat,
			.usage = storageUsage,
			.extent = {32, 32, 1},
			.mipLevels = 1,
			.arrayLayers = 6,
			.debugName = "IBL_IrradianceMap",
		});
		m_irradianceMapView = makeView(m_irradianceMap, createInfo.cubeMapFormat, rhi::ImageViewType::eCube, 1, 6);
		m_irradianceStorageView = makeView(m_irradianceMap, createInfo.cubeMapFormat, rhi::ImageViewType::e2DArray, 1,
		                                   6);

		m_dfgLUT = m_rhiDevice->createTexture(rhi::TextureDesc{
			.dimension = rhi::TextureDimension::e2D,
			.format = createInfo.dfgLUTFormat,
			.usage = storageUsage,
			.extent = {createInfo.dfgLUTSize, createInfo.dfgLUTSize, 1},
			.mipLevels = 1,
			.arrayLayers = 1,
			.debugName = "IBL_DFGLUT",
		});
		m_dfgLUTView = makeView(m_dfgLUT, createInfo.dfgLUTFormat, rhi::ImageViewType::e2D, 1, 1);

		const rhi::TextureSubresourceRange cubeRange = colorRange(m_maxMipLevel + 1, 6);
		const rhi::TextureSubresourceRange irradianceRange = colorRange(1, 6);
		const rhi::TextureSubresourceRange lutRange = colorRange(1, 1);
		imageBarrier(rhiCmd, m_prefilteredMap, cubeRange, rhi::ResourceState::Undefined, rhi::ResourceState::General);
		imageBarrier(rhiCmd, m_irradianceMap, irradianceRange, rhi::ResourceState::Undefined,
		             rhi::ResourceState::General);
		imageBarrier(rhiCmd, m_dfgLUT, lutRange, rhi::ResourceState::Undefined, rhi::ResourceState::General);
		rhiCmd.clearColorTexture(m_prefilteredMap, cubeRange, rhi::ClearColorValue{0.0f, 0.0f, 0.0f, 1.0f});
		rhiCmd.clearColorTexture(m_irradianceMap, irradianceRange, rhi::ClearColorValue{0.0f, 0.0f, 0.0f, 1.0f});
		rhiCmd.clearColorTexture(m_dfgLUT, lutRange, rhi::ClearColorValue{0.5f, 0.5f, 0.0f, 1.0f});
	}

	rhi::PipelineHandle IBLResources::createGenerationPipeline(const uint32_t* spirvCode,
	                                                           size_t spirvSize,
	                                                           const char* entryPoint,
	                                                           rhi::ArgumentLayoutHandle layout,
	                                                           uint32_t variant) const
	{
		const std::array<rhi::ArgumentLayoutHandle, 1> argumentLayouts{{layout}};
		const std::array<rhi::PipelinePushConstantRange, 1> pushConstants{
			{
				rhi::PipelinePushConstantRange{
					.stages = rhi::ShaderStage::compute,
					.offset = 0,
					.size = sizeof(GeneratePushConstants)
				},
			}
		};
		const rhi::ComputePipelineDesc desc{
			.shaderStage =
			rhi::PipelineShaderStageDesc{
				.stage = rhi::ShaderStage::compute,
				.spirvCode = spirvCode,
				.spirvSize = spirvSize,
				.entryPoint = entryPoint,
			},
			.argumentLayouts = argumentLayouts.data(),
			.argumentLayoutCount = static_cast<uint32_t>(argumentLayouts.size()),
			.pushConstantRanges = pushConstants.data(),
			.pushConstantRangeCount = static_cast<uint32_t>(pushConstants.size()),
			.specializationVariant = variant,
		};
		return m_rhiDevice->createComputePipeline(desc);
	}

	void IBLResources::generateIBLMaps(rhi::CommandBuffer& rhiCmd, const CreateInfo& createInfo)
	{
#ifdef USE_SLANG
		rhi::ComputeEncoder* encoder = rhiCmd.beginComputePass();
		if (encoder == nullptr)
		{
			return;
		}
		const auto dispatchGeneration = [&](rhi::PipelineHandle pipeline,
		                                    rhi::ArgumentTableHandle table,
		                                    const GeneratePushConstants& constants,
		                                    uint32_t groupCountX,
		                                    uint32_t groupCountY,
		                                    uint32_t groupCountZ,
											const char* eventName = nullptr
			) -> bool
		{
			if (pipeline.isNull() || table.isNull())
			{
				return false;
			}
			rhiCmd.beginEvent(eventName);
			encoder->setPipeline(pipeline);
			encoder->setArgumentTable(0, table);
			encoder->setRootConstants(0, &constants, sizeof(constants));
			encoder->dispatch(rhi::DispatchDesc{
				.groupCountX = groupCountX, .groupCountY = groupCountY, .groupCountZ = groupCountZ
			});
			rhiCmd.endEvent();
			return true;
		};
		const auto createGenerationTable = [&](rhi::ArgumentLayoutHandle layout,
		                                       const rhi::ArgumentWrite* writes,
		                                       uint32_t writeCount) -> rhi::ArgumentTableHandle
		{
			const rhi::ArgumentTableHandle table = m_rhiDevice->createArgumentTable(layout);
			m_generationArgumentTables.push_back(table);
			if (writeCount > 0)
			{
				m_rhiDevice->updateArgumentTable(table, writeCount, writes);
			}
			return table;
		};

		const std::array<rhi::ArgumentBinding, 2> envToCubeBindings{
			{
				rhi::ArgumentBinding{
					.binding = 0, .type = rhi::ArgumentType::combinedImageSampler,
					.visibility = rhi::ShaderStage::compute
				},
				rhi::ArgumentBinding{
					.binding = 1, .type = rhi::ArgumentType::storageTexture, .visibility = rhi::ShaderStage::compute
				},
			}
		};
		m_envGenerationArgumentLayout = m_rhiDevice->createArgumentLayout(rhi::ArgumentLayoutDesc{
			.bindings = envToCubeBindings.data(), .bindingCount = static_cast<uint32_t>(envToCubeBindings.size()),
			.debugName = "ibl-env-generation"
		});

		const rhi::ArgumentBinding lutBinding{
			.binding = 0, .type = rhi::ArgumentType::storageTexture, .visibility = rhi::ShaderStage::compute
		};
		m_lutGenerationArgumentLayout = m_rhiDevice->createArgumentLayout(rhi::ArgumentLayoutDesc{
			.bindings = &lutBinding, .bindingCount = 1, .debugName = "ibl-lut-generation"
		});

		m_dfgGenerationPipeline =
			createGenerationPipeline(shader_ibl_dfg_slang,
			                         std::size(shader_ibl_dfg_slang) * sizeof(uint32_t),
			                         "dfgLUTMain", m_lutGenerationArgumentLayout, 0x7201u);

		const rhi::ArgumentWrite dfgWrite{
			.binding = 0, .type = rhi::ArgumentType::storageTexture, .textureView = m_dfgLUTView,
			.accessIntent = rhi::ArgumentAccessIntent::readWrite
		};
		const rhi::ArgumentTableHandle dfgTable = createGenerationTable(m_lutGenerationArgumentLayout, &dfgWrite, 1);

		GeneratePushConstants push{
			.width = createInfo.dfgLUTSize,
			.height = createInfo.dfgLUTSize,
			.sampleCount = createInfo.brdfSampleCount,
		};
		if (!dispatchGeneration(m_dfgGenerationPipeline,
		                        dfgTable,
		                        push,
		                        (createInfo.dfgLUTSize + 7u) / 8u,
		                        (createInfo.dfgLUTSize + 7u) / 8u,
		                        1u,"DFG LUT Pass"))
		{
			rhiCmd.endEncoding();
			return;
		}

		if (!createInfo.sourceEnvironmentView.isNull())
		{
			m_irradianceGenerationPipeline =
				createGenerationPipeline(shader_ibl_irradiance_slang,
				                         std::size(shader_ibl_irradiance_slang) * sizeof(uint32_t),
				                         "irradianceConvolutionMain", m_envGenerationArgumentLayout, 0x7202u);
			m_prefilterGenerationPipeline =
				createGenerationPipeline(shader_ibl_prefilter_slang,
				                         std::size(shader_ibl_prefilter_slang) * sizeof(uint32_t),
				                         "prefilterGGXMain", m_envGenerationArgumentLayout, 0x7203u);

			std::array<rhi::ArgumentWrite, 2> writes{
				{
					rhi::ArgumentWrite{
						.binding = 0, .type = rhi::ArgumentType::combinedImageSampler,
						.textureView = createInfo.sourceEnvironmentView, .sampler = m_cubeMapSampler
					},
					rhi::ArgumentWrite{
						.binding = 1, .type = rhi::ArgumentType::storageTexture,
						.textureView = m_irradianceStorageView, .accessIntent = rhi::ArgumentAccessIntent::readWrite
					},
				}
			};
			const rhi::ArgumentTableHandle irradianceTable =
				createGenerationTable(m_envGenerationArgumentLayout, writes.data(),
				                      static_cast<uint32_t>(writes.size()));

			push = GeneratePushConstants{
				.width = 32,
				.height = 32,
				.sourceWidth = createInfo.sourceWidth,
				.sourceHeight = createInfo.sourceHeight,
				.sourceMaxMip = std::max(1u, createInfo.sourceMipCount) - 1u,
				.sampleCount = createInfo.irradianceSampleCount,
			};
			if (!dispatchGeneration(m_irradianceGenerationPipeline,
			                        irradianceTable,
			                        push,
			                        (push.width + 7u) / 8u,
			                        (push.height + 7u) / 8u,
			                        6u, "IBL Irradiance Pass"))
			{
				rhiCmd.endEncoding();
				return;
			}

			for (uint32_t mip = 0; mip <= m_maxMipLevel; ++mip)
			{
				const uint32_t mipSize = std::max(1u, createInfo.cubeMapSize >> mip);
				rhi::TextureViewCreateDesc mipViewDesc{};
				mipViewDesc.image = m_prefilteredMap;
				mipViewDesc.format = createInfo.cubeMapFormat;
				mipViewDesc.viewType = rhi::ImageViewType::e2DArray;
				mipViewDesc.aspect = rhi::TextureAspect::color;
				mipViewDesc.baseMipLevel = mip;
				mipViewDesc.levelCount = 1;
				mipViewDesc.baseArrayLayer = 0;
				mipViewDesc.layerCount = 6;
				const rhi::TextureViewHandle mipView = m_rhiDevice->createTextureView(mipViewDesc);
				m_generationMipViews.push_back(mipView);
				writes = {
					{
						rhi::ArgumentWrite{
							.binding = 0, .type = rhi::ArgumentType::combinedImageSampler,
							.textureView = createInfo.sourceEnvironmentView, .sampler = m_cubeMapSampler
						},
						rhi::ArgumentWrite{
							.binding = 1, .type = rhi::ArgumentType::storageTexture,
							.textureView = mipView, .accessIntent = rhi::ArgumentAccessIntent::readWrite
						},
					}
				};
				const rhi::ArgumentTableHandle prefilterTable =
					createGenerationTable(m_envGenerationArgumentLayout, writes.data(),
					                      static_cast<uint32_t>(writes.size()));

				push = GeneratePushConstants{
					.width = mipSize,
					.height = mipSize,
					.sourceWidth = createInfo.sourceWidth,
					.sourceHeight = createInfo.sourceHeight,
					.sourceMaxMip = std::max(1u, createInfo.sourceMipCount) - 1u,
					.sampleCount = createInfo.prefilterSampleCount,
					.roughness = m_maxMipLevel > 0 ? static_cast<float>(mip) / static_cast<float>(m_maxMipLevel) : 0.0f,
				};
				if (!dispatchGeneration(m_prefilterGenerationPipeline,
				                        prefilterTable,
				                        push,
				                        (mipSize + 7u) / 8u,
				                        (mipSize + 7u) / 8u,
				                        6u, "IBL Diffuse Pass"))
				{
					rhiCmd.endEncoding();
					return;
				}
			}
			m_splitSumReady = true;
		}
		rhiCmd.endEncoding();
#else
		(void)createInfo;
#endif
	}

	void IBLResources::transitionGeneratedImagesForSampling(rhi::CommandBuffer& rhiCmd) const
	{
		imageBarrier(rhiCmd, m_dfgLUT, colorRange(1, 1), rhi::ResourceState::General,
		             rhi::ResourceState::ShaderRead);
		imageBarrier(rhiCmd, m_irradianceMap, colorRange(1, 6), rhi::ResourceState::General,
		             rhi::ResourceState::ShaderRead);
		imageBarrier(rhiCmd, m_prefilteredMap, colorRange(m_maxMipLevel + 1, 6), rhi::ResourceState::General,
		             rhi::ResourceState::ShaderRead);
	}

	void IBLResources::deinit()
	{
		if (m_rhiDevice == nullptr)
		{
			*this = IBLResources{};
			return;
		}

		for (rhi::TextureViewHandle view : m_generationMipViews)
		{
			m_rhiDevice->destroyTextureView(view);
		}
		m_rhiDevice->destroyPipeline(m_prefilterGenerationPipeline);
		m_rhiDevice->destroyPipeline(m_irradianceGenerationPipeline);
		m_rhiDevice->destroyPipeline(m_dfgGenerationPipeline);
		for (rhi::ArgumentTableHandle table : m_generationArgumentTables)
		{
			m_rhiDevice->destroyArgumentTable(table);
		}
		if (!m_lutGenerationArgumentLayout.isNull())
		{
			m_rhiDevice->destroyArgumentLayout(m_lutGenerationArgumentLayout);
		}
		if (!m_envGenerationArgumentLayout.isNull())
		{
			m_rhiDevice->destroyArgumentLayout(m_envGenerationArgumentLayout);
		}

		m_rhiDevice->destroyTextureView(m_prefilteredMapView);
		m_rhiDevice->destroyTextureView(m_irradianceMapView);
		m_rhiDevice->destroyTextureView(m_irradianceStorageView);
		m_rhiDevice->destroyTextureView(m_dfgLUTView);
		m_rhiDevice->destroySampler(m_cubeMapSampler);
		m_rhiDevice->destroySampler(m_lutSampler);
		if (!m_prefilteredMap.isNull())
		{
			m_rhiDevice->destroyTexture(m_prefilteredMap);
		}
		if (!m_irradianceMap.isNull())
		{
			m_rhiDevice->destroyTexture(m_irradianceMap);
		}
		if (!m_dfgLUT.isNull())
		{
			m_rhiDevice->destroyTexture(m_dfgLUT);
		}

		*this = IBLResources{};
	}
} // namespace demo
