if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED VARIABLE_NAME)
  message(FATAL_ERROR "EmbedSpirv.cmake requires INPUT_FILE, OUTPUT_FILE, and VARIABLE_NAME")
endif()

file(READ "${INPUT_FILE}" _spirv_hex HEX)
string(LENGTH "${_spirv_hex}" _spirv_hex_length)
math(EXPR _spirv_remainder "${_spirv_hex_length} % 8")
if(NOT _spirv_remainder EQUAL 0)
  message(FATAL_ERROR "SPIR-V byte size must be divisible by four: ${INPUT_FILE}")
endif()

math(EXPR _spirv_byte_size "${_spirv_hex_length} / 2")
set(_header "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n")
string(APPEND _header "inline constexpr uint32_t ${VARIABLE_NAME}[] = {\n")

if(_spirv_hex_length GREATER 0)
  math(EXPR _last_word_offset "${_spirv_hex_length} - 8")
  set(_column 0)
  foreach(_offset RANGE 0 ${_last_word_offset} 8)
    string(SUBSTRING "${_spirv_hex}" ${_offset} 2 _b0)
    math(EXPR _offset1 "${_offset} + 2")
    math(EXPR _offset2 "${_offset} + 4")
    math(EXPR _offset3 "${_offset} + 6")
    string(SUBSTRING "${_spirv_hex}" ${_offset1} 2 _b1)
    string(SUBSTRING "${_spirv_hex}" ${_offset2} 2 _b2)
    string(SUBSTRING "${_spirv_hex}" ${_offset3} 2 _b3)
    if(_column EQUAL 0)
      string(APPEND _header "  ")
    endif()
    string(APPEND _header "0x${_b3}${_b2}${_b1}${_b0}u, ")
    math(EXPR _column "${_column} + 1")
    if(_column EQUAL 8)
      string(APPEND _header "\n")
      set(_column 0)
    endif()
  endforeach()
  if(NOT _column EQUAL 0)
    string(APPEND _header "\n")
  endif()
endif()

string(APPEND _header "};\n")
string(APPEND _header "inline constexpr size_t ${VARIABLE_NAME}_sizeInBytes = ${_spirv_byte_size}u;\n")
file(WRITE "${OUTPUT_FILE}" "${_header}")
